/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/mobile/reviews/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/mobile/reviews/?branch_ids=1,2&period=30
         *         &sentiment=bad|NEGATIVE,…&status=unread|replied|unanswered&source=app|vk
         *         &checkup_status=in_progress|resolved|rejected|none&q=…&limit=50&offset=0
         *
         *     Возвращает {reviews: Review[], total, limit, offset}. period — целое число
         *     дней (фильтр по last_message_at). Фильтры и пагинация — review_filters.py;
         *     без них ответ тот же, что до 16.09.2026 (весь список).
         */
        get: operations["v1_mobile_reviews_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/reviews/{review_id}/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/v1/mobile/reviews/{id}/messages/ */
        get: operations["v1_mobile_reviews_messages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/reviews/{review_id}/reply/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/mobile/reviews/{review_id}/reply/  body: {text}
         *
         *     Для VK-диалога (есть vk_sender_id) РЕАЛЬНО отправляет сообщение гостю в
         *     ВКонтакте через send_vk_reply (он же сохранит ADMIN_REPLY с vk_message_id
         *     и обновит conv). Для APP-отзыва (нет VK-канала) — сохраняет ответ локально.
         */
        post: operations["v1_mobile_reviews_reply_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/reviews/{review_id}/resolve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/mobile/reviews/{review_id}/resolve/
         *
         *     Помечает обращение как прочитанное (has_unread=False).
         *     Сообщение в VK не отправляется. Не разрешено для негативных VK-отзывов
         *     без ответа — мобайл это валидирует, дублирование тут.
         */
        post: operations["v1_mobile_reviews_resolve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/reviews/{id}/cancel-auto-send/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/mobile/reviews/{pk}/cancel-auto-send/
         *
         *     Отменить запланированный автоответ ИИ («Отменить» из пуша/карточки отзыва).
         *     200 {'ok': True, 'auto_send_status': 'cancelled'} — отменили.
         *     200 {'ok': False, 'auto_send_status': '<текущий>'} — отменять было нечего.
         *     409 — ИИ уже успел отправить ответ.
         */
        post: operations["v1_mobile_reviews_cancel_auto_send_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/reviews/{review_id}/regenerate-draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/analytics/reviews/{review_id}/regenerate-draft/
         *
         *     Генерирует новый AI-черновик ответа для отзыва. Сохраняет в
         *     TestimonialConversation.ai_draft и сбрасывает ai_draft_rejected=False.
         */
        post: operations["v1_analytics_reviews_regenerate_draft_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/reviews/{review_id}/reject-draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/analytics/reviews/{review_id}/reject-draft/
         *
         *     Помечает текущий AI-черновик как отклонённый админом. Сам черновик
         *     остаётся в БД (для аудита), но мобайл больше не показывает его до
         *     регенерации.
         */
        post: operations["v1_analytics_reviews_reject_draft_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/reviews/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/v1/analytics/reviews/summary/?period=30d&branch_ids=1,2 */
        get: operations["v1_analytics_reviews_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/branches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/v1/mobile/branches/ */
        get: operations["v1_mobile_branches_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/branches/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_mobile_branches_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_mobile_branches_partial_update"];
        trace?: never;
    };
    "/api/v1/analytics/auto-reply/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET   /api/v1/analytics/auto-reply/settings/
         *     PATCH /api/v1/analytics/auto-reply/settings/
         *
         *     Singleton-настройки AI-автоответов на отзывы (одна запись на тенант).
         *
         *     Body (PATCH, все поля опциональны):
         *       enabled            — bool, общий рубильник
         *       sentiment_enabled  — dict{POSITIVE,NEGATIVE,PARTIALLY_NEGATIVE,NEUTRAL,PENDING: bool}
         *                           (SPAM всегда выключен — не принимаем в API)
         *       branch_enabled     — dict{branch_id(str): bool}
         *       reminder_minutes   — 30 | 60 | 180 | 720
         *       ai_tone            — 'formal' | 'friendly' | 'neutral'
         *
         *     Автоотправка позитивных ответов (ИИ отвечает сам; дефолт — всё выключено):
         *       auto_send_enabled        — bool, мастер-флаг автоотправки
         *       auto_send_delay_minutes  — 5 | 15 | 30 | 60 (окно отмены)
         *       auto_send_attach_links   — bool, кнопки «Яндекс Карты»/«2ГИС»
         *       auto_send_links_text     — str ≤200, фраза перед кнопками
         *       auto_send_daily_limit    — int 1..500
         *       auto_send_branch_enabled — dict{branch_id(str): bool}
         *
         *     Автоподтверждение на негатив («спасибо, разберёмся»; дефолт выключено):
         *       auto_ack_enabled         — bool
         *       auto_ack_delay_minutes   — 5 | 15 | 30 | 60 | 120 (окно без ответа человека)
         *       auto_ack_text            — str 1..300
         */
        get: operations["v1_analytics_auto_reply_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description GET   /api/v1/analytics/auto-reply/settings/
         *     PATCH /api/v1/analytics/auto-reply/settings/
         *
         *     Singleton-настройки AI-автоответов на отзывы (одна запись на тенант).
         *
         *     Body (PATCH, все поля опциональны):
         *       enabled            — bool, общий рубильник
         *       sentiment_enabled  — dict{POSITIVE,NEGATIVE,PARTIALLY_NEGATIVE,NEUTRAL,PENDING: bool}
         *                           (SPAM всегда выключен — не принимаем в API)
         *       branch_enabled     — dict{branch_id(str): bool}
         *       reminder_minutes   — 30 | 60 | 180 | 720
         *       ai_tone            — 'formal' | 'friendly' | 'neutral'
         *
         *     Автоотправка позитивных ответов (ИИ отвечает сам; дефолт — всё выключено):
         *       auto_send_enabled        — bool, мастер-флаг автоотправки
         *       auto_send_delay_minutes  — 5 | 15 | 30 | 60 (окно отмены)
         *       auto_send_attach_links   — bool, кнопки «Яндекс Карты»/«2ГИС»
         *       auto_send_links_text     — str ≤200, фраза перед кнопками
         *       auto_send_daily_limit    — int 1..500
         *       auto_send_branch_enabled — dict{branch_id(str): bool}
         *
         *     Автоподтверждение на негатив («спасибо, разберёмся»; дефолт выключено):
         *       auto_ack_enabled         — bool
         *       auto_ack_delay_minutes   — 5 | 15 | 30 | 60 | 120 (окно без ответа человека)
         *       auto_ack_text            — str 1..300
         */
        patch: operations["v1_analytics_auto_reply_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/dashboard/today/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/dashboard/today/?branch_ids=1,2
         *
         *     «Задачи дня» для главного экрана: негатив без ответа, черновики ИИ,
         *     запланированные автоответы, коды дня по точкам, срок оплаты сети, топ точек
         *     за 30 дней. Один запрос вместо четырёх, которые собирал клиент.
         */
        get: operations["v1_dashboard_today_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/stats/
         *
         *     Query params:
         *       branch_ids — comma-separated Branch PKs (omit = all branches)
         *       period     — today | 7d | 30d | 90d | year | all  (default: 30d)
         *       start      — YYYY-MM-DD  (overrides period)
         *       end        — YYYY-MM-DD  (overrides period)
         */
        get: operations["v1_analytics_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/stats/slow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/stats/slow/
         *
         *     Returns only the slow-to-compute stats (POS guests + scan index).
         *     Called asynchronously from the dashboard after the page has loaded.
         *
         *     Query params: same as GeneralStatsAPIView (branch_ids, period, start, end)
         */
        get: operations["v1_analytics_stats_slow_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/stats/detail/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/stats/detail/?metric=qr_scans&period=30d&limit=50&offset=0
         *
         *     Список гостей за метрикой общей статистики — те же гости, что на
         *     веб-странице /analytics/stats/detail/ (services.get_stat_clients).
         */
        get: operations["v1_analytics_stats_detail_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/branches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/branches/
         *
         *     Returns all active branches for the branch-filter UI.
         */
        get: operations["v1_analytics_branches_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/guests/?search=&limit=100&offset=0
         *
         *     Все гости тенанта с RF-метриками, монетами и датой последнего визита.
         */
        get: operations["v1_guests_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guests/{vk_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/guests/<vk_id>/
         *
         *     Карточка гостя для мобильного приложения. Агрегирует данные по всем
         *     ClientBranch-профилям гостя в текущем тенанте: баланс монет (income−expense),
         *     RF-сегмент, последние визиты и транзакции, VK-статус, призы и отзывы.
         *
         *     Один гость (guest.Client по vk_id) = одна карточка, даже если он состоит
         *     в нескольких точках сети.
         */
        get: operations["v1_guests_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guests/{vk_id}/adjust-coins/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/guests/<vk_id>/adjust-coins/  body: {amount: int (знаковое), reason: str}
         *
         *     Ручная корректировка баланса монет гостя администратором.
         *     amount > 0 — начисление (income), amount < 0 — списание (expense).
         *     Транзакция привязывается к самому свежему ClientBranch-профилю гостя;
         *     достаточность баланса проверяется по агрегату всех профилей (как его
         *     видит мобайл). Требует право adjust_coins.
         */
        post: operations["v1_guests_adjust_coins_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/rf/
         *
         *     Query params:
         *       branch_ids — comma-separated Branch PKs (omit = all branches)
         *       mode       — restaurant | delivery (default: restaurant)
         *       trend_days — number of days for trend chart (7–365, default: 30)
         *       r_score    — when combined with f_score, returns guest list for that cell
         *       f_score    — see r_score
         */
        get: operations["v1_analytics_rf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/recalculate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/analytics/rf/recalculate/
         *
         *     Synchronously recalculates RF scores for the given branches and mode.
         *     Intended for manual runs from the admin dashboard.
         *
         *     Body (JSON or form):
         *       mode       — restaurant | delivery  (default: restaurant)
         *       branch_ids — comma-separated Branch PKs (omit = all active branches)
         */
        post: operations["v1_analytics_rf_recalculate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/segments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/segments/
         *
         *     Список RF-сегментов для выбора аудитории рассылки.
         *     Возвращает глобальные сегменты (branch=null) + число гостей в каждом.
         */
        get: operations["v1_analytics_segments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/migrations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/rf/migrations/?mode=restaurant&trend_days=30
         *
         *     Полный список миграций между RF-сегментами за период для отдельного
         *     экрана мобильного приложения: [{from, to, count}]. count знаковый —
         *     «+» если гость перешёл в более сильный сегмент (рост по R+F),
         *     «−» если в более слабый (ослабление). Это позволяет мобайлу
         *     фильтровать поток «приток / отток».
         */
        get: operations["v1_analytics_rf_migrations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/send-broadcast/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/analytics/rf/send-broadcast/
         *
         *     Creates a Broadcast + BroadcastSend per branch and sends VK messages.
         *
         *     Accepts both JSON and multipart form data (for image upload).
         *
         *     Body:
         *       segment_id   — RFSegment PK (опционально; без него — рассылка всем оцифрованным)
         *       message_text — broadcast text (required, max 4096 chars)
         *       mode         — restaurant | delivery (default: restaurant)
         *       branch_ids   — comma-separated Branch PKs (omit = все активные)
         *       image        — image file (optional, multipart only)
         *
         *     Если segment_id передан — Broadcast привязывается к указанному RFSegment
         *     (audience_type=ALL + rf_segments=[segment]). Если segment_id опущен —
         *     создаётся Broadcast БЕЗ rf_segments (audience_type=ALL → все оцифрованные
         *     в данной точке).
         */
        post: operations["v1_analytics_rf_send_broadcast_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/generate-broadcast-text/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/analytics/rf/generate-broadcast-text/
         *
         *     Uses Claude AI to generate a broadcast message.
         *
         *     Body (JSON):
         *       segment_id — RFSegment PK (опционально). Если передан — текст пишется
         *                    с подсказкой по сегменту. Без него — общий текст для всех
         *                    оцифрованных гостей.
         */
        post: operations["v1_analytics_rf_generate_broadcast_text_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/campaigns/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/campaigns/?limit=100
         *
         *     История запусков рассылок (BroadcastSend) в формате,
         *     ожидаемом мобильным приложением.
         */
        get: operations["v1_analytics_campaigns_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/campaigns/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description PATCH /api/v1/analytics/campaigns/<pk>/  — изменить текст рассылки через VK API (24ч окно)
         *     DELETE /api/v1/analytics/campaigns/<pk>/ — удалить запись рассылки
         */
        delete: operations["v1_analytics_campaigns_destroy"];
        options?: never;
        head?: never;
        /**
         * @description PATCH /api/v1/analytics/campaigns/<pk>/  — изменить текст рассылки через VK API (24ч окно)
         *     DELETE /api/v1/analytics/campaigns/<pk>/ — удалить запись рассылки
         */
        patch: operations["v1_analytics_campaigns_partial_update"];
        trace?: never;
    };
    "/api/v1/analytics/rf/campaigns/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/v1/analytics/rf/campaigns/   — история кампаний (последние 100)
         *     POST /api/v1/analytics/rf/campaigns/   — создать кампанию и запустить начисление
         *
         *     POST body (JSON):
         *       segment_id     — RFSegment PK (обязателен: кампания всегда из ячейки)
         *       mode           — restaurant | delivery
         *       branch_ids     — CSV точек (как в send-broadcast)
         *       r_score, f_score, expected_count, start, end — контекст ячейки матрицы
         *       reward_type    — gift | points
         *       catalog_item_id — позиция каталога наград (для gift)
         *       points_amount  — целое > 0 (для points)
         *       lifetime_days  — срок забора подарка; 0/пусто — срок позиции
         *       holdout_percent — контрольная группа, % (по умолчанию 10)
         *       name, comment  — опционально
         *
         *     Начисление идёт асинхронно (celery); прогресс — GET detail.
         *     Snapshot аудитории фиксируется здесь и больше не меняется.
         */
        get: operations["v1_analytics_rf_campaigns_retrieve"];
        put?: never;
        /**
         * @description GET  /api/v1/analytics/rf/campaigns/   — история кампаний (последние 100)
         *     POST /api/v1/analytics/rf/campaigns/   — создать кампанию и запустить начисление
         *
         *     POST body (JSON):
         *       segment_id     — RFSegment PK (обязателен: кампания всегда из ячейки)
         *       mode           — restaurant | delivery
         *       branch_ids     — CSV точек (как в send-broadcast)
         *       r_score, f_score, expected_count, start, end — контекст ячейки матрицы
         *       reward_type    — gift | points
         *       catalog_item_id — позиция каталога наград (для gift)
         *       points_amount  — целое > 0 (для points)
         *       lifetime_days  — срок забора подарка; 0/пусто — срок позиции
         *       holdout_percent — контрольная группа, % (по умолчанию 10)
         *       name, comment  — опционально
         *
         *     Начисление идёт асинхронно (celery); прогресс — GET detail.
         *     Snapshot аудитории фиксируется здесь и больше не меняется.
         */
        post: operations["v1_analytics_rf_campaigns_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/campaigns/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/v1/analytics/rf/campaigns/<pk>/ — детали + живые метрики. */
        get: operations["v1_analytics_rf_campaigns_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/campaigns/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/analytics/rf/campaigns/<pk>/cancel/
         *
         *     Отмена кампании (ТЗ §9): начисление останавливается, неактивированные
         *     подарки отзываются с возвратом лимита, баллы откатываются в пределах
         *     неиспользованного остатка. Активированные подарки остаются у гостей.
         */
        post: operations["v1_analytics_rf_campaigns_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/campaigns/kpi/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/rf/campaigns/kpi/?start=YYYY-MM-DD&end=YYYY-MM-DD
         *
         *     Компактный блок «RFM-кампании» для общей панели (ТЗ RFM §7, 4 карточки):
         *       assigned      — уникальные гости, которым успешно начислена награда;
         *       activated     — активировали RFM-подарок (+% от получателей подарков);
         *       returned      — вернулись после награды (+% и сравнение с контролем);
         *       improved      — улучшили RF-позицию (+% от вернувшихся).
         *
         *     Период — по дате создания кампании; по умолчанию последние 30 дней.
         */
        get: operations["v1_analytics_rf_campaigns_kpi_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rf/reward-catalog/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/analytics/rf/reward-catalog/
         *
         *     Позиции «Каталога наград», доступные для назначения RFM-кампанией:
         *     активные, не архивные, available_for_rfm, с привязанным подарком
         *     (без product гостю нечего показать в «Моих подарках»).
         */
        get: operations["v1_analytics_rf_reward_catalog_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Параметры (все необязательные, без них ответ как раньше — последние limit штук):
         *       limit       1..200 (по умолчанию 50)
         *       before_id   курсор: отдать записи со id < before_id (листать историю назад);
         *                   в ответе next_before_id — что передать за следующей страницей
         *       since       ISO-8601: только записи новее этого момента (опрос «что нового»)
         *       type        типы через запятую (review_new,draft_ready,…)
         *       unread=1    только непрочитанные
         *     Курсор по id, а не по offset: уведомления прибывают постоянно, и offset
         *     сдвигал бы страницы. Добавлено 16.09.2026 для колокольчика CheckUp (контракт №17).
         */
        get: operations["v1_notifications_retrieve"];
        put?: never;
        /**
         * @description GET /api/v1/notifications/?limit=50 — история уведомлений текущего пользователя.
         *     POST /api/v1/notifications/ {ids?: [int], all?: true} — отметить прочитанными.
         *
         *     Notification лежит в public schema, поэтому работает из любого тенант-домена.
         */
        post: operations["v1_notifications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/push-prefs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/me/push-prefs/  — текущие настройки + доступные тенанты/типы для UI.
         *     PATCH /api/v1/me/push-prefs/  body: {tenants?: {...}, types?: {...}}
         *
         *     Формат push_prefs (хранится в User.push_prefs JSONField):
         *       {
         *         "tenants": {"asap_orel": true, "shavuha_ot_leo": false, "*": true},
         *         "types":   {"review_new": true, "draft_ready": false}
         *       }
         *
         *     Дефолт (пустой prefs) = все пуши включены.
         */
        get: operations["v1_me_push_prefs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description GET /api/v1/me/push-prefs/  — текущие настройки + доступные тенанты/типы для UI.
         *     PATCH /api/v1/me/push-prefs/  body: {tenants?: {...}, types?: {...}}
         *
         *     Формат push_prefs (хранится в User.push_prefs JSONField):
         *       {
         *         "tenants": {"asap_orel": true, "shavuha_ot_leo": false, "*": true},
         *         "types":   {"review_new": true, "draft_ready": false}
         *       }
         *
         *     Дефолт (пустой prefs) = все пуши включены.
         */
        patch: operations["v1_me_push_prefs_partial_update"];
        trace?: never;
    };
    "/api/v1/push/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/push/register/  body: {token, platform}
         *     DELETE /api/v1/push/register/ body: {token}
         *
         *     Сохраняем Expo/APNs/FCM push-токен в `users.PushToken`. Один user может
         *     иметь несколько токенов (несколько устройств). При повторной регистрации
         *     того же токена — обновляем `last_seen_at` (auto_now=True) и перепривязываем
         *     к текущему user'у на случай переустановки приложения другим админом.
         */
        post: operations["v1_push_register_create"];
        /**
         * @description POST /api/v1/push/register/  body: {token, platform}
         *     DELETE /api/v1/push/register/ body: {token}
         *
         *     Сохраняем Expo/APNs/FCM push-токен в `users.PushToken`. Один user может
         *     иметь несколько токенов (несколько устройств). При повторной регистрации
         *     того же токена — обновляем `last_seen_at` (auto_now=True) и перепривязываем
         *     к текущему user'у на случай переустановки приложения другим админом.
         */
        delete: operations["v1_push_register_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branch/daily-codes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/v1/branch/daily-codes/
         *
         *     Возвращает коды дня за последние 7 дней по всем активным точкам.
         */
        get: operations["v1_branch_daily_codes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branch/daily-codes/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/branch/daily-codes/generate/
         *
         *     Body (JSON):
         *       branch_id — int, обязательно
         *       purpose   — 'BIRTHDAY' | 'SUPERPRIZE' | 'OTHER' (по умолчанию BIRTHDAY)
         *
         *     Ручной/экстренный триггер: создаёт или перегенерирует 5-значный код
         *     для (branch, purpose, today). Возвращает обновлённую запись.
         */
        post: operations["v1_branch_daily_codes_generate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `reply` - ответ ИИ (позитив)
         *     * `ack` - подтверждение «разберёмся» (негатив)
         * @enum {string}
         */
        AutoSendKindEnum: "reply" | "ack";
        /**
         * @description * `scheduled` - Запланирован
         *     * `sent` - Отправлен
         *     * `cancelled` - Отменён
         *     * `skipped` - Пропущен
         *     * `failed` - Ошибка отправки
         * @enum {string}
         */
        AutoSendStatusEnum: "scheduled" | "sent" | "cancelled" | "skipped" | "failed";
        /** @description Product available as a birthday prize. */
        BirthdayProduct: {
            id: number;
            name: string;
            /** @default  */
            description: string;
            readonly image_url: string | null;
            price: number;
        };
        /**
         * @description Birthday status for the frontend.
         *
         *     is_birthday_window — today is within ±5 days of birth_date
         *     already_claimed    — a birthday prize was already claimed this calendar year
         *     can_claim          — all conditions met (window + not claimed + birth_date established ≥30 days)
         */
        BirthdayStatus: {
            is_birthday_window: boolean;
            already_claimed: boolean;
            can_claim: boolean;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        Branch: {
            readonly id: number;
            /**
             * ID точки
             * @description Используется в QR-кодах и ссылках. Задаётся вручную.
             */
            readonly branch_id: number;
            /** Название */
            readonly name: string;
            /**
             * Активна
             * @description Неактивная точка скрыта для гостей.
             */
            readonly is_active: boolean;
            readonly address: string | null;
        };
        /** @description Response for GET /branches/<branch_id>/ */
        BranchInfo: {
            id: number;
            branch_id: number;
            name: string;
            address: string;
            phone: string;
            yandex_map: string;
            gis_map: string;
            logotype_url: string | null;
            coin_icon_url: string | null;
            vk_group_id: number | null;
            vk_group_name: string | null;
            story_image_url: string | null;
            code_prompt_message: string;
            quest_show_message: string;
            brand_color: string;
            brand_color_secondary: string;
            wheel_theme?: string;
        };
        BuyRequest: {
            vk_id: number;
            branch_id: number;
            product_id: number;
        };
        /** @description InventoryItem created after a successful purchase. */
        BuyResponse: {
            id: number;
            product_id: number;
            product_name: string;
            readonly product_image_url: string | null;
            price: number;
            acquired_from: string;
            status: string;
            duration: number;
            /** Format: date-time */
            activated_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
        };
        /**
         * @description * `in_progress` - В работе в CheckUp
         *     * `resolved` - Решено в CheckUp
         *     * `rejected` - Отклонено в CheckUp
         * @enum {string}
         */
        CheckupStatusEnum: "in_progress" | "resolved" | "rejected";
        ClientGetRequest: {
            vk_id: number;
            branch_id: number;
        };
        /**
         * @description Flat response combining ClientBranch + guest.Client + VK subscription status.
         *     Input: ClientBranch with select_related('client', 'vk_status') and _coins_balance annotation.
         */
        ClientProfileResponse: {
            id: number;
            /** Format: date */
            birth_date: string | null;
            is_employee: boolean;
            readonly coins_balance: number;
            vk_id: number;
            first_name: string;
            last_name: string;
            /** Format: uri */
            photo_url: string;
            readonly is_community_member: boolean;
            readonly community_via_app: boolean | null;
            readonly is_newsletter_subscriber: boolean;
            readonly newsletter_via_app: boolean | null;
            readonly is_story_uploaded: boolean;
            readonly story_uploaded_at: string | null;
            readonly vk_bdate: string | null;
        };
        ClientRegistrationRequest: {
            vk_id: number;
            branch_id: number;
            /** @default  */
            first_name: string;
            /** @default  */
            last_name: string;
            /**
             * Format: uri
             * @default
             */
            photo_url: string;
            /** Format: date */
            birth_date?: string | null;
            /** @default restaurant */
            source: components["schemas"]["Source066Enum"];
            invited_by_cb_id?: number | null;
            /** @default  */
            src: string;
        };
        /** @description Guest submits the 5-digit short code from their delivery receipt. */
        CodeActivationRequest: {
            short_code: string;
            vk_id: number;
            branch_id: number;
        };
        /**
         * @description Сетевой резолв: гость вводит код БЕЗ точки (тенант-QR). Точку определяем
         *     по коду среди всех точек тенанта.
         */
        CodeResolveRequest: {
            short_code: string;
            vk_id: number;
        };
        /** @description Response for GET /transactions/ */
        CoinTransaction: {
            id: number;
            type: string;
            source: string;
            amount: number;
            description: string;
            /** Format: date-time */
            created_at: string;
        };
        CooldownRequest: {
            vk_id: number;
            branch_id: number;
        };
        /** @description SHOP cooldown status for a guest. */
        CooldownResponse: {
            is_active: boolean;
            /** Format: date-time */
            expires_at: string;
            readonly seconds_remaining: number;
        };
        /** @description Shared response for webhook registration and code activation. */
        Delivery: {
            id: number;
            short_code: string;
            order_source: string;
            status: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            activated_at: string | null;
        };
        /** @description Response for GET /employees/ — ClientBranch with is_employee=True. */
        Employee: {
            id: number;
            /** Format: date */
            birth_date: string | null;
            readonly coins_balance: number;
            vk_id: number;
            first_name: string;
            last_name: string;
            /** Format: uri */
            photo_url: string;
        };
        /** @description Phase 2: guest claims the reward after the animation completes. */
        GameClaim: {
            session_token: string;
            employee_id?: number | null;
            /** @default false */
            delivery: boolean;
        };
        /** @description GAME cooldown state for a guest. */
        GameCooldown: {
            is_active: boolean;
            /** Format: date-time */
            expires_at: string;
            readonly seconds_remaining: number;
        };
        /** @description Phase 1 response — given to the client before the animation plays. */
        GameSession: {
            session_token: string;
            score: number;
        };
        /** @description Phase 1: guest initiates the game. */
        GameStart: {
            vk_id: number;
            branch_id: number;
            code?: string | null;
            /** @default false */
            delivery: boolean;
        };
        InventoryActivate: {
            vk_id: number;
            branch_id: number;
            item_id: number;
            code?: string | null;
        };
        /** @description INVENTORY cooldown state for a guest. */
        InventoryCooldown: {
            is_active: boolean;
            /** Format: date-time */
            expires_at: string;
            readonly seconds_remaining: number;
        };
        /** @description Single item in a guest's inventory. */
        InventoryItem: {
            id: number;
            product_id?: number | null;
            product_name?: string | null;
            product_description?: string | null;
            readonly product_image_url: string | null;
            acquired_from: string;
            status: string;
            duration: number;
            /** Format: date-time */
            activated_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            claim_expires_at?: string | null;
            days_left_to_claim?: number | null;
            /** @default 0 */
            min_order_amount: number;
            /** @description Активация требует код дня (ДР — код точки, RF/RFM — сетевой). */
            readonly needs_code: boolean;
        };
        InventoryRequest: {
            vk_id: number;
            branch_id: number;
        };
        /**
         * @description * `restaurant` - restaurant
         *     * `delivery` - delivery
         * @enum {string}
         */
        ModeEnum: "restaurant" | "delivery";
        /**
         * @description PATCH: only provided fields are updated.
         *     Not included ≠ set to null — absent fields are simply ignored.
         *
         *     community_via_app=True  → marks community subscription as done via app
         *     newsletter_via_app=True → marks newsletter subscription as done via app
         */
        PatchedClientUpdateRequest: {
            vk_id?: number;
            branch_id?: number;
            first_name?: string | null;
            last_name?: string | null;
            /** Format: uri */
            photo_url?: string | null;
            /** Format: date */
            birth_date?: string | null;
            community_via_app?: boolean | null;
            newsletter_via_app?: boolean | null;
            is_community_member?: boolean | null;
            is_newsletter_subscriber?: boolean | null;
        };
        /**
         * @description * `today` - today
         *     * `7d` - 7d
         *     * `30d` - 30d
         *     * `90d` - 90d
         *     * `year` - year
         *     * `all` - all
         * @enum {string}
         */
        PeriodEnum: "today" | "7d" | "30d" | "90d" | "year" | "all";
        /** @description Single product in the catalog. */
        Product: {
            id: number;
            name: string;
            description: string;
            readonly image_url: string | null;
            price: number;
            is_super_prize: boolean;
            is_birthday_prize: boolean;
            readonly category_id: number | null;
            readonly category_name: string | null;
        };
        /** @description Response for GET /promotions/ */
        Promotion: {
            id: number;
            title: string;
            discount: string;
            dates: string;
            readonly image_url: string | null;
        };
        QuestActivate: {
            vk_id: number;
            branch_id: number;
            quest_id: number;
        };
        /** @description QUEST cooldown state for a guest. */
        QuestCooldown: {
            is_active: boolean;
            /** Format: date-time */
            expires_at: string;
            readonly seconds_remaining: number;
        };
        /** @description Quest with a per-guest completion flag (item in get_quests list). */
        QuestListItem: {
            id: number;
            name: string;
            description: string;
            reward: number;
            completed: boolean;
        };
        QuestRequest: {
            vk_id: number;
            branch_id: number;
        };
        /** @description Active quest submit state returned to the frontend. */
        QuestSubmit: {
            id: number;
            quest_id: number;
            quest_name: string;
            quest_description: string;
            quest_reward: number;
            status: string;
            /** Format: date-time */
            activated_at: string;
            duration: number;
            /** Format: date-time */
            expires_at: string;
            readonly seconds_remaining: number;
        };
        QuestSubmitInput: {
            vk_id: number;
            branch_id: number;
            quest_id: number;
            code: string;
            employee_id?: number | null;
        };
        /** @description Query params for RF analysis endpoint. */
        RFQuery: {
            /** @default  */
            branch_ids: string;
            /** @default 30 */
            trend_days: number;
            /** @default restaurant */
            mode: components["schemas"]["ModeEnum"];
            r_score?: number;
            f_score?: number;
            /** @default 30d */
            period: components["schemas"]["PeriodEnum"];
            /** Format: date */
            start?: string;
            /** Format: date */
            end?: string;
        };
        /**
         * @description Соответствует мобильному `Review` interface.
         *
         *     Сериализатор НЕ создаёт draft-полей (`has_draft`, `draft_text`,
         *     `draft_created_at`) пока их нет в модели. Возвращаем безопасные
         *     дефолты — мобайл это переварит.
         */
        ReviewList: {
            readonly id: number;
            /** @description Главный источник для обратной совместимости: APP приоритетнее. */
            readonly source: string;
            /** @description Все источники: ['APP'] / ['VK_MESSAGE'] / ['APP', 'VK_MESSAGE']. */
            readonly sources: string[];
            readonly sentiment: string;
            /** Комментарий ИИ */
            ai_comment?: string;
            readonly branch_id: number | null;
            readonly branch_name: string;
            readonly customer_name: string;
            /** VK ID отправителя */
            vk_sender_id?: string;
            readonly text: string;
            readonly rating: number | null;
            /** Статус жалобы в CheckUp */
            checkup_status?: components["schemas"]["CheckupStatusEnum"] | components["schemas"]["BlankEnum"];
            /** Вердикт CheckUp */
            checkup_verdict?: string;
            /** Менеджер CheckUp */
            checkup_manager?: string;
            /**
             * Жалоба закрыта в CheckUp
             * Format: date-time
             */
            checkup_resolved_at?: string | null;
            /**
             * Последнее сообщение
             * Format: date-time
             */
            last_message_at?: string | null;
            /** Есть непрочитанные */
            has_unread?: boolean;
            /** Ответ отправлен */
            is_replied?: boolean;
            readonly has_draft: boolean;
            readonly draft_text: string | null;
            readonly draft_created_at: string;
            readonly review_link_yandex: string;
            readonly review_link_2gis: string;
            /**
             * Статус автоответа
             * @description Пусто — автоответ не рассматривался. scheduled — запланирован, sent — отправлен, cancelled — отменён, skipped — не подошёл по условиям, failed — ошибка отправки.
             *
             *     * `scheduled` - Запланирован
             *     * `sent` - Отправлен
             *     * `cancelled` - Отменён
             *     * `skipped` - Пропущен
             *     * `failed` - Ошибка отправки
             */
            auto_send_status?: components["schemas"]["AutoSendStatusEnum"] | components["schemas"]["BlankEnum"];
            readonly auto_send_at: string | null;
            /**
             * Причина
             * @description Почему автоответ пропущен/отменён/упал: manual_reply, needs_human, numeric_only, daily_limit, vk_error: …
             */
            auto_send_reason?: string;
            /**
             * Тип автоответа
             * @description Что именно запланировано/отправлено в auto_send_*: полный ответ ИИ на позитив или короткое автоподтверждение на негатив. Пусто у старых записей = ответ.
             *
             *     * `reply` - ответ ИИ (позитив)
             *     * `ack` - подтверждение «разберёмся» (негатив)
             */
            auto_send_kind?: components["schemas"]["AutoSendKindEnum"] | components["schemas"]["BlankEnum"];
            readonly auto_send_with_links: boolean;
            /**
             * Нужен человек
             * @description ИИ определил, что в отзыве вопрос/просьба — автоответ отправлять нельзя.
             */
            ai_needs_human?: boolean;
            readonly inferred_branch_id: number | null;
            readonly inferred_branch_name: string;
            readonly inferred_table_number: number | null;
            readonly inferred_scan_at: string | null;
            readonly inferred_source: string;
        };
        ReviewMessage: {
            readonly id: number;
            /** Источник */
            readonly source: components["schemas"]["ReviewMessageSourceEnum"];
            /** Текст сообщения */
            readonly text: string;
            /** Оценка (1–5) */
            readonly rating: number | null;
            /**
             * Время
             * Format: date-time
             */
            readonly created_at: string;
            readonly admin_name: string;
            readonly attachments: string;
            /**
             * Отправлено ИИ
             * @description Ответ отправлен автоматически (автоотправка ИИ), а не сотрудником.
             */
            readonly is_ai_generated: boolean;
            /** Контекст (на что ответ) */
            readonly reply_to_text: string;
            /**
             * Время контекста
             * Format: date-time
             */
            readonly reply_to_date: string | null;
            readonly branch_name: string;
            /** Столик */
            readonly table_number: number | null;
        };
        /**
         * @description * `APP` - Из приложения
         *     * `VK_MESSAGE` - ВК сообщение
         *     * `ADMIN_REPLY` - Ответ администратора
         * @enum {string}
         */
        ReviewMessageSourceEnum: "APP" | "VK_MESSAGE" | "ADMIN_REPLY";
        /**
         * @description * `restaurant` - restaurant
         *     * `delivery` - delivery
         *     * `website` - website
         *     * `vk_catalog` - vk_catalog
         *     * `story` - story
         *     * `rfm` - rfm
         * @enum {string}
         */
        Source066Enum: "restaurant" | "delivery" | "website" | "vk_catalog" | "story" | "rfm";
        StoryAccess: {
            enabled: boolean;
            can_play: boolean;
            already_played: boolean;
            status: string;
            has_gifts: boolean;
        };
        StoryActivate: {
            vk_id: number;
            branch_id: number;
            code?: string | null;
        };
        /**
         * @description Подарок из сториз в «Мои подарки».
         *
         *     Контекст:
         *       request  — для абсолютного URL картинки
         *       settings — резолв story-настроек (для условий и текста инструкции)
         */
        StoryGift: {
            id: number;
            status: string;
            status_label: string;
            /** @default story */
            source: string;
            /** @default  */
            campaign_key: string;
            product_id?: number | null;
            product_name?: string | null;
            product_description?: string | null;
            readonly product_image_url: string | null;
            min_order_amount: number;
            duration: number;
            /** Format: date-time */
            activated_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
            readonly seconds_remaining: number;
            /** Format: date-time */
            claim_expires_at: string | null;
            days_left_to_claim: number | null;
            readonly cafe_address: string;
            readonly activation_text: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Подарок из набора сториз (для экрана выбора). */
        StoryProduct: {
            id: number;
            name: string;
            /** @default  */
            description: string;
            /** @default  */
            emoji: string;
            readonly image_url: string | null;
        };
        StoryRequest: {
            vk_id: number;
            branch_id: number;
        };
        StorySelect: {
            vk_id: number;
            branch_id: number;
            product_id: number;
        };
        SuperPrizeClaim: {
            vk_id: number;
            branch_id: number;
            product_id: number;
        };
        /**
         * @description SuperPrizeEntry response.
         *
         *     - status == 'pending'  → product is null, available_products is populated
         *     - status == 'claimed'  → product holds the chosen item, available_products is []
         *     - status == 'issued'   → same as claimed
         *     - status == 'expired'  → product is null, available_products is []
         */
        SuperPrizeEntry: {
            id: number;
            acquired_from: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            claimed_at: string | null;
            readonly product: {
                [key: string]: unknown;
            } | null;
            readonly available_products: unknown[];
        };
        /**
         * @description POST /api/v1/testimonials/
         *     Принимает отзыв из мини-приложения ВКонтакте.
         */
        TestimonialCreate: {
            /** @description VK ID гостя из мини-приложения */
            vk_id: number;
            /** @description branch_id торговой точки */
            branch_id: number;
            /** @description Текст отзыва */
            review: string;
            rating?: number | null;
            /** @default  */
            phone: string;
            table?: number | null;
        };
        /**
         * @description POST /api/v1/vk/auth/
         *
         *     VK ID OAuth2 PKCE — параметры для server-side обмена кода на токен.
         *
         *     code          — authorization code из redirect-callback VK.
         *     device_id     — device_id из того же callback (привязан к PKCE сессии).
         *     code_verifier — PKCE code_verifier, сгенерированный фронтом перед OAuth2 запросом.
         *     redirect_uri  — тот же redirect_uri, что использовался при инициации OAuth2.
         *     branch_id     — ID торговой точки из QR-кода.
         *     birth_date    — дата рождения (заполняется при онбординге).
         */
        VKAuthRequest: {
            code: string;
            device_id: string;
            code_verifier: string;
            /** Format: uri */
            redirect_uri: string;
            state: string;
            branch_id: number;
            /** Format: date */
            birth_date?: string | null;
            /** @default restaurant */
            source: components["schemas"]["Source066Enum"];
            /** @default  */
            src: string;
        };
        /**
         * @description Ответ POST /api/v1/vk/auth/ — профиль гостя + токен веб-сессии.
         *
         *     Только для схемы (drf-spectacular): сам ответ вьюха собирает из
         *     `ClientProfileResponseSerializer` и дописывает два поля — токен выдаётся
         *     после сериализации профиля и не должен утекать в остальные эндпоинты,
         *     которые используют тот же профильный сериализатор.
         *
         *     web_token            — доказательство личности вне ВК (заголовок
         *                            `X-Web-Session`, см. apps/shared/guest/web_session.py);
         *     web_token_expires_at — ISO-8601, когда токен протухнет.
         */
        VKAuthResponse: {
            id: number;
            /** Format: date */
            birth_date: string | null;
            is_employee: boolean;
            readonly coins_balance: number;
            vk_id: number;
            first_name: string;
            last_name: string;
            /** Format: uri */
            photo_url: string;
            readonly is_community_member: boolean;
            readonly community_via_app: boolean | null;
            readonly is_newsletter_subscriber: boolean;
            readonly newsletter_via_app: boolean | null;
            readonly is_story_uploaded: boolean;
            readonly story_uploaded_at: string | null;
            readonly vk_bdate: string | null;
            readonly web_token: string;
            /** Format: date-time */
            readonly web_token_expires_at: string;
        };
        /** @description POST /api/v1/vk/story/ — mark that the guest published a VK story. */
        VKStoryRequest: {
            vk_id: number;
            branch_id: number;
        };
        /** @description Response for POST /api/v1/vk/story/ */
        VKStoryResponse: {
            is_story_uploaded: boolean;
            /** Format: date-time */
            story_uploaded_at: string | null;
            first_upload: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_mobile_reviews_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewList"][];
                };
            };
        };
    };
    v1_mobile_reviews_messages_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewMessage"][];
                };
            };
        };
    };
    v1_mobile_reviews_reply_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_mobile_reviews_resolve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_mobile_reviews_cancel_auto_send_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_reviews_regenerate_draft_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_reviews_reject_draft_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_reviews_summary_retrieve: {
        parameters: {
            query?: {
                /** @description id точек через запятую (пересекается с правами) */
                branch_ids?: string;
                end?: string;
                /** @description today|7d|30d|90d|year|all (по умолчанию 30d) */
                period?: "30d" | "7d" | "90d" | "all" | "today" | "year";
                /** @description YYYY-MM-DD (вместе с end перекрывает period) */
                start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_mobile_branches_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
        };
    };
    v1_mobile_branches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_mobile_branches_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_auto_reply_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_auto_reply_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_dashboard_today_retrieve: {
        parameters: {
            query?: {
                /** @description id точек через запятую (пересекается с правами) */
                branch_ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_stats_retrieve: {
        parameters: {
            query?: {
                branch_ids?: string;
                end?: string;
                /**
                 * @description * `today` - today
                 *     * `7d` - 7d
                 *     * `30d` - 30d
                 *     * `90d` - 90d
                 *     * `year` - year
                 *     * `all` - all
                 */
                period?: "today" | "7d" | "30d" | "90d" | "year" | "all";
                start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_stats_slow_retrieve: {
        parameters: {
            query?: {
                branch_ids?: string;
                end?: string;
                /**
                 * @description * `today` - today
                 *     * `7d` - 7d
                 *     * `30d` - 30d
                 *     * `90d` - 90d
                 *     * `year` - year
                 *     * `all` - all
                 */
                period?: "today" | "7d" | "30d" | "90d" | "year" | "all";
                start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_stats_detail_retrieve: {
        parameters: {
            query: {
                /** @description id точек через запятую (пересекается с правами) */
                branch_ids?: string;
                end?: string;
                /** @description 1..200; без limit — до 200 */
                limit?: number;
                /** @description ключ метрики из GET /analytics/stats/ (см. metrics в ответе 400) */
                metric: string;
                offset?: number;
                /** @description today|7d|30d|90d|year|all (по умолчанию 30d) */
                period?: "30d" | "7d" | "90d" | "all" | "today" | "year";
                /** @description YYYY-MM-DD (вместе с end перекрывает period) */
                start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_branches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_guests_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_guests_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vk_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_guests_adjust_coins_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vk_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_rf_retrieve: {
        parameters: {
            query?: {
                branch_ids?: string;
                end?: string;
                f_score?: number;
                /**
                 * @description * `restaurant` - restaurant
                 *     * `delivery` - delivery
                 */
                mode?: "restaurant" | "delivery";
                /**
                 * @description * `today` - today
                 *     * `7d` - 7d
                 *     * `30d` - 30d
                 *     * `90d` - 90d
                 *     * `year` - year
                 *     * `all` - all
                 */
                period?: "today" | "7d" | "30d" | "90d" | "year" | "all";
                r_score?: number;
                start?: string;
                trend_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_rf_recalculate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RFQuery"];
                "application/x-www-form-urlencoded": components["schemas"]["RFQuery"];
                "multipart/form-data": components["schemas"]["RFQuery"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_segments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_rf_migrations_retrieve: {
        parameters: {
            query?: {
                branch_ids?: string;
                end?: string;
                f_score?: number;
                /**
                 * @description * `restaurant` - restaurant
                 *     * `delivery` - delivery
                 */
                mode?: "restaurant" | "delivery";
                /**
                 * @description * `today` - today
                 *     * `7d` - 7d
                 *     * `30d` - 30d
                 *     * `90d` - 90d
                 *     * `year` - year
                 *     * `all` - all
                 */
                period?: "today" | "7d" | "30d" | "90d" | "year" | "all";
                r_score?: number;
                start?: string;
                trend_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_rf_send_broadcast_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_rf_generate_broadcast_text_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_campaigns_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_campaigns_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_campaigns_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_analytics_rf_campaigns_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_rf_campaigns_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_rf_campaigns_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_rf_campaigns_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_rf_campaigns_kpi_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_analytics_rf_reward_catalog_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_notifications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_notifications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_me_push_prefs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_me_push_prefs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_push_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_push_register_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_branch_daily_codes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_branch_daily_codes_generate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
