# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(help_text='Полный код из POS-системы.', max_length=512, unique=True, verbose_name='Код доставки')),
                ('short_code', models.CharField(editable=False, help_text='Последние 5 символов кода. Устанавливается автоматически.', max_length=5, verbose_name='Короткий код')),
                ('order_source', models.CharField(choices=[('iiko', 'iiko'), ('dooglys', 'Dooglys')], max_length=20, verbose_name='Источник заказа')),
                ('duration', models.PositiveIntegerField(default=5, help_text='Часов, в течение которых клиент может активировать код.', verbose_name='Длительность (ч)')),
                ('expires_at', models.DateTimeField(help_text='Устанавливается автоматически: created_at + duration ч.', verbose_name='Действителен до')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Активирован')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_deliveries', to='branch.clientbranch', verbose_name='Активировал')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'short_code'], name='delivery_branch_short_idx'), models.Index(fields=['expires_at'], name='delivery_expires_idx'), models.Index(fields=['order_source', 'created_at'], name='delivery_source_time_idx'), models.Index(fields=['activated_by'], name='delivery_activated_by_idx')],
            },
        ),
    ]
