# Generated by Django 6.0.3 on 2026-04-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='duration',
            field=models.PositiveIntegerField(default=8, help_text='Часов, в течение которых клиент может активировать код.', verbose_name='Длительность (ч)'),
        ),
    ]
