# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text='Внутреннее название для удобства — гости не видят.', max_length=255, verbose_name='Название')),
                ('bot_username', models.CharField(help_text='Username без @, например: my_restaurant_bot', max_length=255, verbose_name='Username бота')),
                ('api', models.CharField(help_text='Токен от @BotFather. Храните в секрете.', max_length=512, verbose_name='API Token')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Telegram-бот',
                'verbose_name_plural': 'Telegram-боты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('chat_id', models.BigIntegerField(blank=True, help_text='Заполняется автоматически при подключении через бота.', null=True, verbose_name='Chat ID')),
                ('verification_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Токен верификации')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите флаг, чтобы отключить уведомления без удаления записи.', verbose_name='Активен')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='telegram.telegrambot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Администратор бота',
                'verbose_name_plural': 'Администраторы бота',
                'ordering': ['name'],
            },
        ),
    ]
