# Generated by Django 6.0.3 on 2026-10-04 21:02

import apps.shared.secret_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='api',
            field=apps.shared.secret_fields.EncryptedSecretField(help_text='Токен от @BotFather. Храните в секрете.', max_length=512, verbose_name='API Token'),
        ),
    ]
