# Generated by Django 6.0.3 on 2026-04-15 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0003_testimonialmessage_read_at'),
        ('catalog', '0002_productbranch_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePromoConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Офлайн-промо включено')),
                ('congratulation_text', models.TextField(blank=True, default='Поздравляем, вы выиграли! Выберите свой приз. Подарок будет доступен в течение 10 дней.', help_text='Показывается гостю после игры. Можно использовать эмодзи.', verbose_name='Текст поздравления')),
                ('min_order_text', models.CharField(blank=True, default='', help_text='Например: «при заказе от 500 ₽». Показывается под текстом поздравления.', max_length=255, verbose_name='Условие (мин. заказ)')),
                ('gift_validity_days', models.PositiveIntegerField(default=10, help_text='По умолчанию 10 дней.', verbose_name='Срок действия подарка (дней)')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_promo_config', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Настройки офлайн-промо',
                'verbose_name_plural': 'Настройки офлайн-промо',
            },
        ),
        migrations.CreateModel(
            name='OfflinePromoGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Источник трафика')),
                ('congratulation_text', models.TextField(blank=True, default='', help_text='Если пусто, используется текст по умолчанию.', verbose_name='Текст поздравления')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('expires_at', models.DateTimeField(help_text='Автоматически: received_at + 10 дней.', verbose_name='Действителен до')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Дата и время, когда гость забрал подарок в кафе.', null=True, verbose_name='Активирован в кафе')),
                ('activated_branch', models.ForeignKey(blank=True, help_text='Кафе, в котором гость забрал подарок.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_gift_activations', to='branch.branch', verbose_name='Точка активации')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_promo_gift', to='branch.clientbranch', verbose_name='Гость')),
                ('product', models.ForeignKey(blank=True, help_text='Приз, который гость выбрал после игры.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_promo_gifts', to='catalog.product', verbose_name='Выбранный подарок')),
            ],
            options={
                'verbose_name': 'Подарок (офлайн)',
                'verbose_name_plural': 'Подарки (офлайн)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='opromo_gift_expires_idx'), models.Index(fields=['activated_at'], name='opromo_gift_activated_idx'), models.Index(fields=['source', 'created_at'], name='opromo_gift_source_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflinePromoScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source', models.CharField(blank=True, db_index=True, default='', help_text='Рекламный носитель: листовка, баннер, стойка и т.д. Передаётся через параметр ?promo_source= в QR-коде.', max_length=100, verbose_name='Источник трафика')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_promo_scans', to='branch.clientbranch', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Сканирование (офлайн)',
                'verbose_name_plural': 'Сканирования (офлайн)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='opromo_scan_client_idx'), models.Index(fields=['source', 'created_at'], name='opromo_scan_source_idx'), models.Index(fields=['created_at'], name='opromo_scan_time_idx')],
            },
        ),
    ]
