# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('branch_id', models.PositiveIntegerField(help_text='Используется в QR-кодах и ссылках. Задаётся вручную.', unique=True, verbose_name='ID точки')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Для внутреннего пользования. Не отображается в приложении.', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивная точка скрыта для гостей.', verbose_name='Активна')),
                ('iiko_organization_id', models.CharField(blank=True, help_text='UUID организации из ЛК iiko. Нужен для OLAP-отчётов по этой точке.', max_length=255, verbose_name='IIKO Organization ID')),
                ('dooglys_branch_id', models.PositiveIntegerField(blank=True, help_text='Числовой ID заведения из кабинета Dooglys.', null=True, unique=True, verbose_name='Dooglys Branch ID')),
                ('dooglys_sale_point_id', models.CharField(blank=True, help_text='ID кассовой точки в Dooglys.', max_length=255, null=True, unique=True, verbose_name='Dooglys Sale Point ID')),
                ('story_image', models.ImageField(blank=True, help_text='Изображение-шаблон, которое гость видит перед публикацией VK-сторис.', null=True, upload_to='branch/stories/', verbose_name='Фото для сториса')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('address', models.CharField(blank=True, help_text='Отображается в приложении под названием точки.', max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, help_text='Основной контактный номер точки.', max_length=50, verbose_name='Телефон')),
                ('yandex_map', models.URLField(blank=True, help_text='Ссылка на точку в Яндекс Картах.', verbose_name='Яндекс Карты')),
                ('gis_map', models.URLField(blank=True, help_text='Ссылка на точку в 2ГИС.', verbose_name='2ГИС')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Настройки точки',
                'verbose_name_plural': 'Настройки точек',
            },
        ),
        migrations.CreateModel(
            name='ClientBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('birth_date', models.DateField(blank=True, help_text='Используется для поздравлений и персональных акций.', null=True, verbose_name='Дата рождения')),
                ('birth_date_set_at', models.DateField(blank=True, editable=False, help_text='Устанавливается автоматически при первой записи birth_date. Используется для защиты от злоупотреблений: ДР-приз доступен только если дата установлена не менее 30 дней назад.', null=True, verbose_name='Дата установки ДР')),
                ('is_employee', models.BooleanField(default=False, help_text='Сотрудники исключаются из статистики и акций.', verbose_name='Сотрудник')),
                ('notes', models.TextField(blank=True, help_text='Внутренние заметки. Гость их не видит.', verbose_name='Заметки')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='branch.branch', verbose_name='Торговая точка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_profiles', to='guest.client', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Профиль гостя',
                'verbose_name_plural': 'Профили гостей',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(help_text='Заголовок акции, который видит гость в приложении.', max_length=100, verbose_name='Название')),
                ('discount', models.CharField(help_text='Описание условий акции, например: «−20% на всё меню».', verbose_name='Акция')),
                ('dates', models.CharField(help_text='Период действия, например: «01.06 – 30.06».', max_length=255, verbose_name='Даты')),
                ('images', models.ImageField(help_text='Баннер акции, отображается в приложении.', upload_to='promotions', verbose_name='Фото')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки и промоакции',
            },
        ),
        migrations.CreateModel(
            name='TestimonialConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('vk_sender_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='VK ID отправителя')),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Позитивный'), ('NEGATIVE', 'Негативный'), ('PARTIALLY_NEGATIVE', 'Частично негативный'), ('NEUTRAL', 'Нейтральный'), ('SPAM', 'Спам / Не по теме'), ('WAITING', 'Ожидает анализа')], default='WAITING', max_length=20, verbose_name='Тональность (ИИ)')),
                ('ai_comment', models.TextField(blank=True, verbose_name='Комментарий ИИ')),
                ('has_unread', models.BooleanField(default=True, verbose_name='Есть непрочитанные')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Ответ отправлен')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее сообщение')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='branch.branch', verbose_name='Торговая точка')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='branch.clientbranch', verbose_name='Гость (если зарегистрирован)')),
            ],
            options={
                'verbose_name': 'Отзыв / Обращение',
                'verbose_name_plural': 'Отзывы и Обращения',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('APP', 'Из приложения'), ('VK_MESSAGE', 'ВК сообщение'), ('ADMIN_REPLY', 'Ответ администратора')], max_length=20, verbose_name='Источник')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка (1–5)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('table_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Столик')),
                ('vk_message_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='VK ID сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='branch.testimonialconversation', verbose_name='Переписка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientBranchVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Время визита')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='branch.clientbranch', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Визит гостя',
                'verbose_name_plural': 'Визиты гостей',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['client', '-visited_at'], name='visit_client_time_idx'), models.Index(fields=['visited_at'], name='visit_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientVKStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_community_member', models.BooleanField(default=False, verbose_name='Подписан на сообщество')),
                ('community_joined_at', models.DateTimeField(blank=True, help_text='Когда мы впервые зафиксировали подписку. NULL — ещё не подписан.', null=True, verbose_name='Дата подписки (сообщество)')),
                ('community_via_app', models.BooleanField(blank=True, help_text='null — не подписан; false — до приложения; true — через приложение.', null=True, verbose_name='Через приложение (сообщество)')),
                ('is_newsletter_subscriber', models.BooleanField(default=False, verbose_name='Подписан на рассылку')),
                ('newsletter_joined_at', models.DateTimeField(blank=True, help_text='Когда мы впервые зафиксировали подписку. NULL — ещё не подписан.', null=True, verbose_name='Дата подписки (рассылка)')),
                ('newsletter_via_app', models.BooleanField(blank=True, help_text='null — не подписан; false — до приложения; true — через приложение.', null=True, verbose_name='Через приложение (рассылка)')),
                ('is_story_uploaded', models.BooleanField(default=False, help_text='True — гость хотя бы раз опубликовал наш шаблон сторис через приложение.', verbose_name='Опубликовал сторис')),
                ('story_uploaded_at', models.DateTimeField(blank=True, help_text='Когда впервые опубликовал сторис через приложение. NULL — ни разу.', null=True, verbose_name='Дата публикации сторис')),
                ('checked_at', models.DateTimeField(auto_now=True, help_text='Когда последний раз синхронизировали статус с VK API.', verbose_name='Последняя проверка')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vk_status', to='branch.clientbranch', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'VK-статус гостя',
                'verbose_name_plural': 'VK-статусы гостей',
                'indexes': [models.Index(fields=['is_community_member'], name='vk_community_idx'), models.Index(fields=['is_newsletter_subscriber'], name='vk_newsletter_idx'), models.Index(fields=['community_via_app'], name='vk_comm_via_app_idx'), models.Index(fields=['newsletter_via_app'], name='vk_news_via_app_idx'), models.Index(fields=['is_story_uploaded'], name='vk_story_idx'), models.Index(fields=['story_uploaded_at'], name='vk_story_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Начисление'), ('expense', 'Списание')], max_length=10, verbose_name='Тип')),
                ('source', models.CharField(choices=[('game', 'Игра'), ('quest', 'Квест'), ('shop', 'Магазин'), ('birthday', 'День рождения'), ('delivery', 'Доставка'), ('manual', 'Вручную')], max_length=20, verbose_name='Источник')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма (монет)')),
                ('description', models.CharField(blank=True, help_text='Для ручных операций — причина. Для автоматических — ID связанного объекта.', max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='branch.clientbranch', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Транзакция монет',
                'verbose_name_plural': 'Транзакции монет',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='tx_client_time_idx'), models.Index(fields=['client', 'type'], name='tx_client_type_idx'), models.Index(fields=['source', 'created_at'], name='tx_source_time_idx'), models.Index(fields=['type', 'created_at'], name='tx_type_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('feature', models.CharField(choices=[('game', 'Игра'), ('inventory', 'Инвентарь'), ('shop', 'Магазин'), ('quest', 'Квесты')], max_length=20, verbose_name='Функция')),
                ('last_activated_at', models.DateTimeField(verbose_name='Последняя активация')),
                ('duration', models.PositiveIntegerField(default=18, help_text='Часов после активации, в течение которых фича заблокирована.', verbose_name='Длительность (ч)')),
                ('expires_at', models.DateTimeField(help_text='Устанавливается автоматически: last_activated_at + duration ч.', verbose_name='Разблокируется')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooldowns', to='branch.clientbranch', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Перезарядка',
                'verbose_name_plural': 'Перезарядки',
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['client', 'feature'], name='cooldown_client_feature_idx'), models.Index(fields=['expires_at'], name='cooldown_expires_idx'), models.Index(fields=['feature', 'expires_at'], name='cooldown_feature_exp_idx')],
                'unique_together': {('client', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='DailyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('purpose', models.CharField(choices=[('game', 'Игра'), ('quest', 'Квест'), ('birthday', 'День рождения')], max_length=20, verbose_name='Назначение')),
                ('code', models.CharField(help_text='5-значный цифровой код.', max_length=5, verbose_name='Код')),
                ('valid_date', models.DateField(db_index=True, help_text='День, на который действует код.', verbose_name='Дата')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_codes', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Код дня',
                'verbose_name_plural': 'Коды дня',
                'ordering': ['-valid_date', 'branch__name', 'purpose'],
                'unique_together': {('branch', 'purpose', 'valid_date')},
            },
        ),
        migrations.AddIndex(
            model_name='testimonialconversation',
            index=models.Index(fields=['branch', 'has_unread'], name='testimonial_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonialconversation',
            index=models.Index(fields=['branch', 'vk_sender_id'], name='testimonial_sender_idx'),
        ),
    ]
