# Generated by Django 6.0.3 on 2026-03-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_cointransaction_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Заполняется Celery-задачей при обнаружении прочтения через VK API.', null=True, verbose_name='Прочитано'),
        ),
    ]
