# Generated by Django 6.0.3 on 2026-04-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_testimonialmessage_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbranch',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='ClientBranch гостя, который пригласил через сторис. Устанавливается только при первой регистрации.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_guests', to='branch.clientbranch', verbose_name='Пригласил'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='discount',
            field=models.CharField(help_text='Описание условий акции, например: «−20% на всё меню».', max_length=500, verbose_name='Акция'),
        ),
    ]
