# Generated by Django 6.0.3 on 2026-04-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_clientbranch_invited_by_alter_promotions_discount'),
        ('guest', '0003_alter_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialconversation',
            name='vk_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_conversations', to='guest.client', verbose_name='VK гость (из группы, без точки)'),
        ),
    ]
