# Generated by Django 6.0.3 on 2026-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0019_testimonialmessage_reply_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchconfig',
            name='story_activation_text',
            field=models.TextField(blank=True, default='', help_text='Перезаписывает текст инструкции только для этой точки. Пусто = текст сети.', verbose_name='Текст инструкции перед активацией, сториз (для этой точки)'),
        ),
        migrations.AddField(
            model_name='branchconfig',
            name='story_cafe_address',
            field=models.CharField(blank=True, default='', help_text='Пусто = адрес точки / значение сети.', max_length=255, verbose_name='Адрес кафе для подарка из сториз (для этой точки)'),
        ),
        migrations.AddField(
            model_name='branchconfig',
            name='story_game_enabled',
            field=models.BooleanField(blank=True, help_text='Пусто = использовать значение сети. Да/Нет = переопределить только для этой точки.', null=True, verbose_name='Игра через сториз (для этой точки)'),
        ),
        migrations.AddField(
            model_name='branchconfig',
            name='story_min_order_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто = использовать значение сети.', null=True, verbose_name='Мин. сумма заказа из сториз, ₽ (для этой точки)'),
        ),
        migrations.AddField(
            model_name='branchconfig',
            name='story_saved_text',
            field=models.TextField(blank=True, default='', help_text='Пусто = текст сети.', verbose_name='Текст уведомления после выбора, сториз (для этой точки)'),
        ),
    ]
