# Generated by Django 6.0.3 on 2026-06-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0023_branch_review_links_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvkstatus',
            name='community_source',
            field=models.CharField(blank=True, choices=[('cafe', 'Кафе'), ('delivery', 'Доставка'), ('story', 'Сториз'), ('website', 'Сайт')], db_index=True, help_text='Откуда подписался: кафе / доставка / сториз. Заполняется при via_app-подписке.', max_length=16, null=True, verbose_name='Источник подписки (сообщество)'),
        ),
        migrations.AlterField(
            model_name='clientvkstatus',
            name='newsletter_source',
            field=models.CharField(blank=True, choices=[('cafe', 'Кафе'), ('delivery', 'Доставка'), ('story', 'Сториз'), ('website', 'Сайт')], db_index=True, help_text='Откуда подписался: кафе / доставка / сториз. Заполняется при via_app-подписке.', max_length=16, null=True, verbose_name='Источник подписки (рассылка)'),
        ),
    ]
