# Generated by Django 6.0.3 on 2026-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0027_alter_qrcode_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='mode',
            field=models.CharField(choices=[('cafe', 'В кафе (на месте)'), ('delivery', 'Доставка'), ('delivery_network', 'Доставка — вся сеть (один QR)'), ('website', 'С сайта (сетевой подарок)')], default='cafe', help_text='«Доставка» добавляет delivery=true. «С сайта» добавляет web=<метка> (игра с сайта → сетевой подарок, забор в любой точке по её коду дня).', max_length=16, verbose_name='Тип ссылки'),
        ),
    ]
