# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, help_text='Меньшее значение отображается выше.', verbose_name='Порядок')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(help_text='Количество баллов, которое списывается при покупке. 0 — бесплатно.', verbose_name='Цена (баллы)')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивный товар не виден гостям.', verbose_name='Активен')),
                ('is_super_prize', models.BooleanField(default=False, help_text='Входит в пул суперпризов — может быть выдан при достижении цели.', verbose_name='Суперприз')),
                ('is_birthday_prize', models.BooleanField(default=False, help_text='Доступен как поздравительный подарок в день рождения гостя.', verbose_name='Подарок на ДР')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, help_text='Меньшее значение отображается выше в списке.', verbose_name='Порядок')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='branch.branch', verbose_name='Торговая точка')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['branch', 'ordering'], name='catalog_cat_branch_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'is_active', 'ordering'], name='catalog_prod_branch_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'is_super_prize'], name='catalog_prod_branch_super_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'is_birthday_prize'], name='catalog_prod_branch_bday_idx'),
        ),
    ]
