# Generated by Django 6.0.3 on 2026-03-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, help_text='Меньшее значение отображается выше в списке.', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивный товар скрыт в каталоге призов (магазине), но остаётся доступен как суперприз и именинный приз.', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Назначение в точку',
                'verbose_name_plural': 'Назначения в точки',
                'ordering': ['ordering'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Подарок', 'verbose_name_plural': 'Подарки'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_prod_branch_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_prod_branch_super_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_prod_branch_bday_idx',
        ),
        migrations.AddField(
            model_name='productbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='branch.branch', verbose_name='Торговая точка'),
        ),
        migrations.AddField(
            model_name='productbranch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_assignments', to='catalog.productcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='productbranch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to='catalog.product', verbose_name='Подарок'),
        ),
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalog.ProductBranch', to='branch.branch', verbose_name='Торговые точки'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_super_prize'], name='catalog_prod_super_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_birthday_prize'], name='catalog_prod_bday_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ordering',
        ),
        migrations.AddIndex(
            model_name='productbranch',
            index=models.Index(fields=['branch', 'is_active', 'ordering'], name='catalog_pb_branch_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productbranch',
            index=models.Index(fields=['branch', 'product'], name='catalog_pb_branch_product_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbranch',
            unique_together={('product', 'branch')},
        ),
    ]
