# Generated by Django 6.0.3 on 2026-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_story_prize',
            field=models.BooleanField(default=False, help_text='Входит в отдельный набор подарков для внешних пользователей, пришедших по сториз. НЕ смешивается с супер-призами основной игры. Пул для точки = подарки с этим флагом, подключённые к точке.', verbose_name='Подарок для игры через сториз'),
        ),
    ]
