# Generated by Django 6.0.3 on 2026-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryclaim',
            name='vk_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='VK ID гостя'),
        ),
        migrations.AlterField(
            model_name='discoveryevent',
            name='vk_id',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='VK ID гостя'),
        ),
    ]
