# Generated by Django 6.0.3 on 2026-10-04 21:02

import apps.shared.secret_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0002_alter_wall_token_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketersettings',
            name='vk_wall_token',
            field=apps.shared.secret_fields.EncryptedSecretField(blank=True, help_text='Токен с правом «Стена»: токен сообщества (Управление → Работа с API → Ключи доступа, галочка «Стена») или пользовательский токен админа. НЕ senler-токен (у того «Сообщения» — каналы изолированы). Пусто — посты остаются черновиками, публикация недоступна.', max_length=512, verbose_name='Токен для стены'),
        ),
    ]
