# Generated by Django 6.0.3 on 2026-03-13 01:21

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(help_text='Загрузите Word-документ (.docx) или текстовый файл (.txt) с инструкциями.', upload_to='knowledge_base/', verbose_name='Файл (.docx / .txt)')),
                ('extracted_text', models.TextField(blank=True, help_text='Заполняется автоматически при сохранении файла.', verbose_name='Извлечённый текст')),
                ('is_active', models.BooleanField(default=True, help_text='Только активные документы передаются ИИ в качестве инструкций.', verbose_name='Используется в анализе')),
            ],
            options={
                'verbose_name': 'Документ базы знаний',
                'verbose_name_plural': 'База знаний (инструкции для ИИ)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('recency_min', models.IntegerField(default=0, help_text='Нижняя граница дней с последнего визита (включительно).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Давность: от (дней)')),
                ('recency_max', models.IntegerField(default=9999, help_text='Верхняя граница дней с последнего визита (включительно).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Давность: до (дней)')),
                ('frequency_min', models.IntegerField(default=0, help_text='Минимальное кол-во визитов за период (включительно).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Частота: от (визитов)')),
                ('frequency_max', models.IntegerField(default=9999, help_text='Максимальное кол-во визитов за период (включительно).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Частота: до (визитов)')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('color', colorfield.fields.ColorField(default='#417690', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('strategy', models.TextField(verbose_name='Маркетинговая стратегия')),
                ('hint', models.TextField(blank=True, help_text='Краткая инструкция менеджеру. Отображается в таблице сегментов.', verbose_name='Подсказка для персонала')),
                ('last_campaign_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней рассылки')),
            ],
            options={
                'verbose_name': 'RF-сегмент',
                'verbose_name_plural': 'RF-сегменты',
                'ordering': ['recency_min', 'frequency_min'],
            },
        ),
        migrations.CreateModel(
            name='RFSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('analysis_period', models.PositiveIntegerField(default=365, help_text='Учитываются визиты за последние N дней.', verbose_name='Период анализа (дней)')),
                ('stats_reset_date', models.DateTimeField(blank=True, help_text='Если задана — RF-анализ и общая статистика учитывают ТОЛЬКО данные после этой даты. Балансы монет, задания и инвентарь НЕ затрагиваются.', null=True, verbose_name='Дата обнуления статистики')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rf_settings', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'RF-настройки',
                'verbose_name_plural': 'RF-настройки',
            },
        ),
        migrations.CreateModel(
            name='POSGuestCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('guest_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во гостей')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_guest_cache', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Кэш POS гостей',
                'verbose_name_plural': 'Кэш POS гостей',
                'indexes': [models.Index(fields=['branch', 'date'], name='pos_cache_branch_date_idx')],
                'unique_together': {('branch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RFMigrationLogDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Мигрировал')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rf_migrations_delivery', to='branch.clientbranch', verbose_name='Гость')),
                ('from_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_migrations_from', to='analytics.rfsegment', verbose_name='Из сегмента')),
                ('to_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_migrations_to', to='analytics.rfsegment', verbose_name='В сегмент')),
            ],
            options={
                'verbose_name': 'RF-миграция (доставка)',
                'verbose_name_plural': 'RF-миграции (доставка)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='rf_del_mig_client_idx'), models.Index(fields=['to_segment', 'created_at'], name='rf_del_mig_to_seg_idx')],
            },
        ),
        migrations.CreateModel(
            name='RFMigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Мигрировал')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rf_migrations', to='branch.clientbranch', verbose_name='Гость')),
                ('from_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrations_from', to='analytics.rfsegment', verbose_name='Из сегмента')),
                ('to_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrations_to', to='analytics.rfsegment', verbose_name='В сегмент')),
            ],
            options={
                'verbose_name': 'RF-миграция',
                'verbose_name_plural': 'RF-миграции',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='rf_mig_client_idx'), models.Index(fields=['to_segment', 'created_at'], name='rf_mig_to_seg_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuestRFScoreDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_days', models.PositiveIntegerField(help_text='Дней с последней активации доставки.', verbose_name='Давность (дней)')),
                ('frequency', models.PositiveIntegerField(help_text='Кол-во активаций доставки за период анализа.', verbose_name='Частота (заказов)')),
                ('r_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='R-балл')),
                ('f_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='F-балл')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Рассчитано')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rf_score_delivery', to='branch.clientbranch', verbose_name='Гость')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_guests', to='analytics.rfsegment', verbose_name='Сегмент')),
            ],
            options={
                'verbose_name': 'RF-метрика гостя (доставка)',
                'verbose_name_plural': 'RF-метрики гостей (доставка)',
                'indexes': [models.Index(fields=['r_score', 'f_score'], name='rf_del_score_rf_idx'), models.Index(fields=['segment'], name='rf_del_segment_idx'), models.Index(fields=['calculated_at'], name='rf_del_calc_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuestRFScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_days', models.PositiveIntegerField(help_text='Дней с последнего визита на момент расчёта.', verbose_name='Давность (дней)')),
                ('frequency', models.PositiveIntegerField(help_text='Кол-во визитов за период анализа.', verbose_name='Частота (визитов)')),
                ('r_score', models.PositiveSmallIntegerField(help_text='Балл давности (1 = давно, выше = недавнее).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='R-балл')),
                ('f_score', models.PositiveSmallIntegerField(help_text='Балл частоты (1 = редко, выше = чаще).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='F-балл')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Рассчитано')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rf_score', to='branch.clientbranch', verbose_name='Гость')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='analytics.rfsegment', verbose_name='Сегмент')),
            ],
            options={
                'verbose_name': 'RF-метрика гостя',
                'verbose_name_plural': 'RF-метрики гостей',
                'indexes': [models.Index(fields=['r_score', 'f_score'], name='rf_score_rf_idx'), models.Index(fields=['segment'], name='rf_score_segment_idx'), models.Index(fields=['calculated_at'], name='rf_score_calc_idx')],
            },
        ),
        migrations.CreateModel(
            name='BranchSegmentSnapshotDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('guests_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во гостей')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_snapshots_delivery', to='branch.branch', verbose_name='Торговая точка')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_snapshots', to='analytics.rfsegment', verbose_name='Сегмент')),
            ],
            options={
                'verbose_name': 'Снапшот сегмента (доставка)',
                'verbose_name_plural': 'Снапшоты сегментов (доставка)',
                'ordering': ['-date', 'branch', 'segment'],
                'indexes': [models.Index(fields=['branch', 'date'], name='snap_del_branch_date_idx'), models.Index(fields=['segment', 'date'], name='snap_del_segment_date_idx')],
                'unique_together': {('branch', 'segment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BranchSegmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('guests_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во гостей')),
                ('date', models.DateField(db_index=True, help_text='Дата расчёта снапшота.', verbose_name='Дата')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_snapshots', to='branch.branch', verbose_name='Торговая точка')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.rfsegment', verbose_name='Сегмент')),
            ],
            options={
                'verbose_name': 'Снапшот сегмента',
                'verbose_name_plural': 'Снапшоты сегментов',
                'ordering': ['-date', 'branch', 'segment'],
                'indexes': [models.Index(fields=['branch', 'date'], name='snapshot_branch_date_idx'), models.Index(fields=['segment', 'date'], name='snapshot_segment_date_idx')],
                'unique_together': {('branch', 'segment', 'date')},
            },
        ),
    ]
