# Generated by Django 6.0.3 on 2026-04-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('guest', '0003_alter_client_gender'),
    ]

    operations = [
        migrations.RunSQL(
            "TRUNCATE analytics_guestrfscore, analytics_guestrfscoredelivery, "
            "analytics_rfmigrationlog, analytics_rfmigrationlogdelivery CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='guestrfscore',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rf_score', to='guest.client', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='guestrfscoredelivery',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rf_score_delivery', to='guest.client', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='rfmigrationlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rf_migrations', to='guest.client', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='rfmigrationlogdelivery',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rf_migrations_delivery', to='guest.client', verbose_name='Гость'),
        ),
    ]
