# Generated by Django 6.0.3 on 2026-05-05 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_guestrfscore_client_and_more'),
        ('branch', '0006_alter_testimonialconversation_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfsettings',
            name='f_moderate_max',
            field=models.PositiveIntegerField(default=5, help_text='Граница F2: больше «F1 до» и не больше этого числа. Гости с большим числом визитов попадают в F3 «Часто».', verbose_name='F2 «Умеренно»: до (визитов)'),
        ),
        migrations.AddField(
            model_name='rfsettings',
            name='f_rare_max',
            field=models.PositiveIntegerField(default=3, help_text='Гость попадает в F1, если визитов НЕ БОЛЕЕ этого числа.', verbose_name='F1 «Редко»: до (визитов)'),
        ),
        migrations.AddField(
            model_name='rfsettings',
            name='r_cooling_max',
            field=models.PositiveIntegerField(default=60, help_text='Граница R1: больше «R2 до» и не больше этого числа. Гости с большей давностью попадают в R0 «Холодный».', verbose_name='R1 «Остывший»: до (дней)'),
        ),
        migrations.AddField(
            model_name='rfsettings',
            name='r_fresh_max',
            field=models.PositiveIntegerField(default=14, help_text='Гость попадает в R3, если с последнего визита прошло НЕ БОЛЕЕ этого числа дней.', verbose_name='R3 «Свежий»: до (дней)'),
        ),
        migrations.AddField(
            model_name='rfsettings',
            name='r_warm_max',
            field=models.PositiveIntegerField(default=30, help_text='Граница R2: больше «R3 до» и не больше этого числа.', verbose_name='R2 «Тёплый»: до (дней)'),
        ),
        migrations.AlterField(
            model_name='rfsettings',
            name='branch',
            field=models.OneToOneField(blank=True, help_text='Оставьте пустым, чтобы создать общие настройки для режима «Все точки». Допустима только одна запись с пустым полем.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rf_settings', to='branch.branch', verbose_name='Торговая точка'),
        ),
        migrations.AddConstraint(
            model_name='rfsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('branch',), name='analytics_rfsettings_one_global'),
        ),
    ]
