# Generated by Django 6.0.3 on 2026-05-06 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rfsettings_f_moderate_max_rfsettings_f_rare_max_and_more'),
        ('branch', '0006_alter_testimonialconversation_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfsegment',
            options={'ordering': ['branch__name', 'recency_min', 'frequency_min'], 'verbose_name': 'RF-сегмент', 'verbose_name_plural': 'RF-сегменты'},
        ),
        migrations.AddField(
            model_name='rfsegment',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, чтобы создать общий сегмент для всей сети. Если у точки задан собственный сегмент с тем же кодом — используется он, иначе берётся общий.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rf_segments', to='branch.branch', verbose_name='Торговая точка'),
        ),
        migrations.AlterField(
            model_name='rfsegment',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Код'),
        ),
        migrations.AddConstraint(
            model_name='rfsegment',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'code'), name='analytics_rfsegment_branch_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rfsegment',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('code',), name='analytics_rfsegment_global_code_uniq'),
        ),
    ]
