# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBroadcastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('type', models.CharField(choices=[('birthday_7d', 'За 7 дней до дня рождения'), ('birthday_1d', 'За 1 день до дня рождения'), ('birthday', 'День рождения'), ('after_game_3h', 'Через 3 часа после игры')], max_length=16, unique=True, verbose_name='Триггер')),
                ('message_text', models.TextField(help_text='Лимит VK: 4096 символов.', verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auto_broadcasts/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите флаг, чтобы временно отключить этот триггер.', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон авторассылки',
                'verbose_name_plural': 'Шаблоны авторассылок',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='AutoBroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('birthday_7d', 'За 7 дней до дня рождения'), ('birthday_1d', 'За 1 день до дня рождения'), ('birthday', 'День рождения'), ('after_game_3h', 'Через 3 часа после игры')], db_index=True, max_length=16, verbose_name='Триггер')),
                ('vk_id', models.PositiveIntegerField(db_index=True, verbose_name='VK ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Лог авторассылки',
                'verbose_name_plural': 'Лог авторассылок',
                'indexes': [models.Index(fields=['trigger_type', 'vk_id', 'sent_at'], name='autobc_log_idx')],
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text='Только для администратора — гости не видят это поле.', max_length=255, verbose_name='Название')),
                ('message_text', models.TextField(help_text='Лимит VK: 4096 символов.', verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, help_text='Прикрепляется к сообщению как фото.', null=True, upload_to='broadcasts/', verbose_name='Изображение')),
                ('audience_type', models.CharField(choices=[('all', 'Все оцифрованные'), ('specific', 'Конкретные пользователи')], default='all', max_length=8, verbose_name='Тип аудитории')),
                ('gender_filter', models.CharField(choices=[('all', 'Все'), ('m', 'Мужчины'), ('f', 'Женщины')], default='all', max_length=3, verbose_name='Пол')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='branch.branch', verbose_name='Торговая точка')),
                ('rf_segments', models.ManyToManyField(blank=True, help_text='Оставьте пустым — получат все. Выберите несколько — OR между ними.', related_name='broadcasts', to='analytics.rfsegment', verbose_name='RF-сегменты')),
                ('specific_clients', models.ManyToManyField(blank=True, help_text='Фильтры пола и RF-сегментов игнорируются.', related_name='targeted_broadcasts', to='branch.clientbranch', verbose_name='Конкретные гости')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Отправляется'), ('done', 'Завершена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=9, verbose_name='Статус')),
                ('trigger_type', models.CharField(choices=[('manual', 'Вручную'), ('auto', 'Автоматически')], default='manual', max_length=6, verbose_name='Тип запуска')),
                ('triggered_by', models.CharField(blank=True, help_text='Логин администратора или имя системной задачи.', max_length=255, verbose_name='Запустил')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Получателей')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('auto_broadcast_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sends', to='senler.autobroadcasttemplate', verbose_name='Шаблон авторассылки')),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='senler.broadcast', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Запуск рассылки',
                'verbose_name_plural': 'История рассылок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.PositiveIntegerField(verbose_name='VK ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущен')], default='pending', max_length=7, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('error', models.CharField(blank=True, max_length=512, verbose_name='Ошибка')),
                ('client_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_broadcasts', to='branch.clientbranch', verbose_name='Гость')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='senler.broadcastsend', verbose_name='Запуск')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='SenlerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('vk_group_id', models.PositiveBigIntegerField(help_text='Числовой ID VK-сообщества (без минуса).', verbose_name='ID группы VK')),
                ('vk_community_token', models.CharField(help_text='Community access token — НЕ пользовательский токен.', max_length=512, verbose_name='Токен сообщества VK')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите флаг, чтобы отключить рассылки без удаления настроек.', verbose_name='Активна')),
                ('vk_callback_confirmation', models.CharField(blank=True, help_text='VK → Управление → Работа с API → Callback API → Строка для ответа на подтверждение.', max_length=64, verbose_name='Строка подтверждения Callback')),
                ('vk_callback_secret', models.CharField(blank=True, help_text='Произвольная строка — вводится в VK и проверяется при входящих событиях.', max_length=64, verbose_name='Секрет Callback')),
                ('notes', models.TextField(blank=True, help_text='Внутренние комментарии для администратора.', verbose_name='Заметки')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senler_config', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Настройки рассылки VK',
                'verbose_name_plural': 'Настройки рассылки VK',
            },
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['branch', '-created_at'], name='broadcast_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastsend',
            index=models.Index(fields=['broadcast', '-created_at'], name='bsend_broadcast_date_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastsend',
            index=models.Index(fields=['status'], name='bsend_status_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['send', 'status'], name='brecip_send_status_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['vk_id'], name='brecip_vkid_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['client_branch'], name='brecip_cb_idx'),
        ),
    ]
