# Generated by Django 6.0.3 on 2026-03-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senlerconfig',
            name='longpoll_ts',
            field=models.CharField(blank=True, default='', help_text='Последний обработанный ts VK Group Long Poll. Используется для catchup после простоя.', max_length=32, verbose_name='Long Poll ts'),
        ),
    ]
