# Generated by Django 6.0.3 on 2026-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senler', '0002_senlerconfig_longpoll_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastrecipient',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Когда сообщение было прочитано (из VK API).', null=True, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='vk_message_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID сообщения из ответа messages.send — для отслеживания прочтений.', null=True, verbose_name='VK message ID'),
        ),
    ]
