# Generated by Django 6.0.3 on 2026-07-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senler', '0003_broadcastrecipient_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobroadcastlog',
            name='trigger_type',
            field=models.CharField(choices=[('birthday_7d', 'За 7 дней до дня рождения'), ('birthday_1d', 'За 1 день до дня рождения'), ('birthday', 'День рождения'), ('after_game_3h', 'Через 3 часа после игры'), ('gift_not_claimed', 'Подарок из сториз/сайта не забран')], db_index=True, max_length=32, verbose_name='Триггер'),
        ),
        migrations.AlterField(
            model_name='autobroadcasttemplate',
            name='message_text',
            field=models.TextField(help_text='Лимит VK: 4096 символов. Для триггера «Подарок из сториз/сайта не забран» можно вставлять переменные: {дней_осталось} — сколько дней осталось забрать подарок; {подарок} — название подарка; {адреса} — список адресов всех точек (подарок сетевой — забрать можно в любой). Пример: «Ваш подарок {подарок} всё ещё ждёт вас! Осталось {дней_осталось} дн. Приходите в любое наше кафе: {адреса}».', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='autobroadcasttemplate',
            name='type',
            field=models.CharField(choices=[('birthday_7d', 'За 7 дней до дня рождения'), ('birthday_1d', 'За 1 день до дня рождения'), ('birthday', 'День рождения'), ('after_game_3h', 'Через 3 часа после игры'), ('gift_not_claimed', 'Подарок из сториз/сайта не забран')], max_length=32, unique=True, verbose_name='Триггер'),
        ),
    ]
