# Generated by Django 6.0.3 on 2026-07-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_dailyorderstat'),
        ('branch', '0027_alter_qrcode_mode'),
        ('senler', '0004_alter_autobroadcastlog_trigger_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobroadcastlog',
            name='entity_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Например gift:123 — дедуп по конкретному подарку, а не по периоду.', max_length=64, verbose_name='Ключ объекта'),
        ),
        migrations.CreateModel(
            name='AutoBroadcastRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text='Только для админки — гости его не видят. Напр. «Напоминание о подарке».', max_length=120, verbose_name='Название')),
                ('event', models.CharField(choices=[('birthday_7d', 'За 7 дней до дня рождения'), ('birthday_1d', 'За 1 день до дня рождения'), ('birthday', 'День рождения'), ('after_game_3h', 'Через 3 часа после игры'), ('gift_not_claimed', 'Подарок из сториз/сайта не забран')], db_index=True, help_text='Что должно произойти с гостем, чтобы ему ушло это сообщение.', max_length=32, verbose_name='Событие (триггер)')),
                ('delay_days', models.PositiveSmallIntegerField(blank=True, help_text='Пусто — задержка по умолчанию для этого события (напр. 10 дней для незабранного подарка берётся из настроек сети).', null=True, verbose_name='Задержка после события, дней')),
                ('send_hour_start', models.PositiveSmallIntegerField(default=9, help_text='Тихие часы. По умолчанию 9 — до 9 утра сообщения не уходят.', verbose_name='Не слать раньше (час)')),
                ('send_hour_end', models.PositiveSmallIntegerField(default=21, help_text='По умолчанию 21 — после 21:00 сообщения не уходят.', verbose_name='Не слать позже (час)')),
                ('active_from', models.DateField(blank=True, help_text='Пусто — без ограничения.', null=True, verbose_name='Действует с')),
                ('active_to', models.DateField(blank=True, help_text='Пусто — без ограничения.', null=True, verbose_name='Действует по')),
                ('gender_filter', models.CharField(choices=[('all', 'Все'), ('m', 'Мужчины'), ('f', 'Женщины')], default='all', max_length=3, verbose_name='Пол')),
                ('message_text', models.TextField(help_text='Лимит VK: 4096 символов. Переменные: {имя} — имя гостя; {подарок} — название подарка; {дней_осталось} — сколько дней осталось забрать; {адреса} — адреса всех точек. Доступность переменной зависит от события.', verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auto_broadcasts/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=False, help_text='Пока выключено — сообщения не уходят. Перед включением посмотрите предпросмотр «кому уйдёт».', verbose_name='Активно')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Если на одно событие несколько правил — гость получит сообщение по правилу с БОЛЬШИМ приоритетом (одно сообщение, не несколько).', verbose_name='Приоритет')),
                ('branches', models.ManyToManyField(blank=True, help_text='Пусто — все точки сети.', related_name='auto_broadcast_rules', to='branch.branch', verbose_name='Точки')),
                ('rf_segments', models.ManyToManyField(blank=True, help_text='Пусто — без ограничения по сегменту.', related_name='auto_broadcast_rules', to='analytics.rfsegment', verbose_name='RF-сегменты')),
            ],
            options={
                'verbose_name': 'Правило авторассылки',
                'verbose_name_plural': 'Авторассылки (конструктор)',
                'ordering': ['event', '-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='autobroadcastlog',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='senler.autobroadcastrule', verbose_name='Правило'),
        ),
        migrations.AddIndex(
            model_name='autobroadcastlog',
            index=models.Index(fields=['trigger_type', 'entity_key'], name='autobc_log_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='autobroadcastrule',
            index=models.Index(fields=['event', 'is_active'], name='autobc_rule_event_idx'),
        ),
    ]
