# Generated by Django 6.0.3 on 2026-07-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senler', '0007_alter_autobroadcastlog_trigger_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobroadcastrule',
            name='follow_up_condition',
            field=models.CharField(blank=True, choices=[('not_read', 'Не прочитал сообщение'), ('not_visited', 'Не пришёл в кафе после сообщения')], default='not_read', help_text='Кого догоняем: кто не прочитал, или кто прочитал, но так и не пришёл.', max_length=16, verbose_name='Условие догона'),
        ),
        migrations.AddField(
            model_name='autobroadcastrule',
            name='parent_rule',
            field=models.ForeignKey(blank=True, help_text='Только для события «Догоняющее». Возьмём тех, кому это правило отправило сообщение, и кто не отреагировал.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='senler.autobroadcastrule', verbose_name='За каким правилом догоняем'),
        ),
        migrations.AddField(
            model_name='broadcastsend',
            name='auto_broadcast_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sends', to='senler.autobroadcastrule', verbose_name='Правило авторассылки'),
        ),
        migrations.AlterField(
            model_name='autobroadcastlog',
            name='trigger_type',
            field=models.CharField(choices=[('birthday_7d', 'За 7 дней до дня рождения'), ('birthday_1d', 'За 1 день до дня рождения'), ('birthday', 'День рождения'), ('after_game_3h', 'Через 3 часа после игры'), ('gift_not_claimed', 'Подарок из сториз/сайта не забран'), ('no_visit_days', 'Не приходил N дней (реактивация)'), ('subscribed_days', 'Подписался N дней назад (welcome)'), ('follow_up', 'Догоняющее (не отреагировал на другое правило)')], db_index=True, max_length=32, verbose_name='Триггер'),
        ),
        migrations.AlterField(
            model_name='autobroadcastrule',
            name='event',
            field=models.CharField(choices=[('birthday_7d', 'За 7 дней до дня рождения'), ('birthday_1d', 'За 1 день до дня рождения'), ('birthday', 'День рождения'), ('after_game_3h', 'Через 3 часа после игры'), ('gift_not_claimed', 'Подарок из сториз/сайта не забран'), ('no_visit_days', 'Не приходил N дней (реактивация)'), ('subscribed_days', 'Подписался N дней назад (welcome)'), ('follow_up', 'Догоняющее (не отреагировал на другое правило)')], db_index=True, help_text='Что должно произойти с гостем, чтобы ему ушло это сообщение.', max_length=32, verbose_name='Событие (триггер)'),
        ),
        migrations.AlterField(
            model_name='autobroadcasttemplate',
            name='type',
            field=models.CharField(choices=[('birthday_7d', 'За 7 дней до дня рождения'), ('birthday_1d', 'За 1 день до дня рождения'), ('birthday', 'День рождения'), ('after_game_3h', 'Через 3 часа после игры'), ('gift_not_claimed', 'Подарок из сториз/сайта не забран'), ('no_visit_days', 'Не приходил N дней (реактивация)'), ('subscribed_days', 'Подписался N дней назад (welcome)'), ('follow_up', 'Догоняющее (не отреагировал на другое правило)')], max_length=32, unique=True, verbose_name='Триггер'),
        ),
        migrations.CreateModel(
            name='AutoBroadcastVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text='Напр. «А — со скидкой», «Б — без скидки».', max_length=60, verbose_name='Название варианта')),
                ('message_text', models.TextField(help_text='Переменные те же, что у правила.', verbose_name='Текст варианта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auto_broadcasts/', verbose_name='Изображение')),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Доля аудитории. Два варианта с весами 1 и 1 → 50/50; 3 и 1 → 75/25.', verbose_name='Вес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Участвует в тесте')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='senler.autobroadcastrule', verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Вариант текста (A/B)',
                'verbose_name_plural': 'Варианты текста (A/B)',
                'ordering': ['rule', 'name'],
            },
        ),
        migrations.AddField(
            model_name='broadcastsend',
            name='auto_broadcast_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sends', to='senler.autobroadcastvariant', verbose_name='Вариант текста (A/B)'),
        ),
    ]
