# Generated by Django 6.0.3 on 2026-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senler', '0010_autobroadcastrule_gift_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobroadcastlog',
            name='vk_id',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='VK ID'),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='vk_id',
            field=models.PositiveBigIntegerField(verbose_name='VK ID'),
        ),
    ]
