# Generated by Django 6.0.3 on 2026-10-04 21:02

import apps.shared.secret_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senler', '0014_autobroadcastrule_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senlerconfig',
            name='vk_callback_secret',
            field=apps.shared.secret_fields.EncryptedSecretField(blank=True, help_text='Произвольная строка — вводится в VK и проверяется при входящих событиях.', max_length=64, verbose_name='Секрет Callback'),
        ),
        migrations.AlterField(
            model_name='senlerconfig',
            name='vk_community_token',
            field=apps.shared.secret_fields.EncryptedSecretField(help_text='Community access token — НЕ пользовательский токен.', max_length=512, verbose_name='Токен сообщества VK'),
        ),
    ]
