# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('acquired_from', models.CharField(choices=[('purchase', 'Покупка за баллы'), ('super_prize', 'Суперприз'), ('birthday', 'Подарок на ДР'), ('manual', 'Выдано вручную')], max_length=20, verbose_name='Способ получения')),
                ('description', models.TextField(blank=True, help_text='Только для внутреннего использования.', verbose_name='Заметка')),
                ('duration', models.PositiveIntegerField(default=40, help_text='Сколько минут действителен приз после активации. 0 — без ограничения.', verbose_name='Длительность (мин)')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Активирован')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Устанавливается автоматически при активации.', null=True, verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('client_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='branch.clientbranch', verbose_name='Гость')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.product', verbose_name='Приз')),
            ],
            options={
                'verbose_name': 'Приз гостя',
                'verbose_name_plural': 'Призы гостей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_branch', 'used_at'], name='inventory_client_used_idx'), models.Index(fields=['client_branch', 'activated_at'], name='inventory_client_act_idx'), models.Index(fields=['product', 'acquired_from'], name='inventory_prod_source_idx'), models.Index(fields=['expires_at'], name='inventory_expires_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuperPrizeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('acquired_from', models.CharField(choices=[('game', 'Игра'), ('manual', 'В ручную'), ('birthday', 'День Рождения')], max_length=20, verbose_name='Источник получения')),
                ('description', models.TextField(blank=True, help_text='Например: «Достигнуто 10 посещений». Только для внутреннего использования.', verbose_name='Заметка')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Срок, до которого гость должен сделать выбор. Пусто — бессрочно.', null=True, verbose_name='Действителен до')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Приз выбран')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдан')),
                ('client_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_prizes', to='branch.clientbranch', verbose_name='Гость')),
                ('product', models.ForeignKey(blank=True, help_text='Заполняется когда гость делает выбор из пула суперпризов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_prize_claims', to='catalog.product', verbose_name='Выбранный приз')),
            ],
            options={
                'verbose_name': 'Суперприз',
                'verbose_name_plural': 'Суперпризы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_branch', 'issued_at'], name='sp_client_issued_idx'), models.Index(fields=['client_branch', 'claimed_at'], name='sp_client_claimed_idx'), models.Index(fields=['expires_at'], name='sp_expires_idx'), models.Index(fields=['product', 'acquired_from'], name='sp_product_trigger_idx')],
            },
        ),
    ]
