# Generated by Django 6.0.3 on 2026-06-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0020_branchconfig_story_activation_text_and_more'),
        ('catalog', '0005_product_is_story_prize'),
        ('inventory', '0002_alter_inventoryitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGiftEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('played_at', models.DateTimeField(blank=True, null=True, verbose_name='Сыграл story-игру')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='Подарок выбран')),
                ('received_at', models.DateTimeField(blank=True, help_text='Момент фиксации метрики «Получили подарок через сториз».', null=True, verbose_name='Сохранён в «Мои подарки»')),
                ('duration', models.PositiveIntegerField(default=40, help_text='Сколько минут действует подарок после активации в кафе.', verbose_name='Длительность после активации (мин)')),
                ('min_order_amount', models.PositiveIntegerField(default=0, help_text='Снимок минимальной суммы заказа на момент получения.', verbose_name='Мин. сумма заказа, ₽')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Заполняется ТОЛЬКО после ввода кода дня в кафе. Метрика «Активировали через сториз».', null=True, verbose_name='Активирован в кафе')),
                ('expires_at', models.DateTimeField(blank=True, help_text='activated_at + duration. Ставится автоматически при активации.', null=True, verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдан сотрудником')),
                ('campaign_key', models.CharField(blank=True, default='', help_text='Опционально: идентификатор кампании или сториз для аналитики.', max_length=64, verbose_name='Ключ кампании/сториз')),
                ('client_branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story_gift', to='branch.clientbranch', verbose_name='Гость')),
                ('product', models.ForeignKey(blank=True, help_text='Из набора подарков для сториз (is_story_prize=True).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_gift_claims', to='catalog.product', verbose_name='Выбранный подарок')),
            ],
            options={
                'verbose_name': 'Подарок из сториз',
                'verbose_name_plural': 'Подарки из сториз',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['received_at'], name='story_received_idx'), models.Index(fields=['activated_at'], name='story_activated_idx'), models.Index(fields=['expires_at'], name='story_expires_idx')],
            },
        ),
    ]
