# Generated by Django 6.0.3 on 2026-07-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0027_alter_qrcode_mode'),
        ('inventory', '0005_giftcostevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygiftentry',
            name='claim_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='received_at + срок жизни (настройка сети). Если не активировали до этого момента — подарок сгорает. Пусто — бессрочно (подарки, выданные до включения срока).', null=True, verbose_name='Забрать до'),
        ),
        migrations.AddField(
            model_name='storygiftentry',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Когда ушла авторассылка «подарок не забран». Дедуп: одно на подарок.', null=True, verbose_name='Напоминание отправлено'),
        ),
        migrations.AlterField(
            model_name='storygiftentry',
            name='activated_branch',
            field=models.ForeignKey(blank=True, help_text='Точка, где забрали подарок по её коду дня. Подарок сетевой — забрать можно в любой точке, независимо от источника. Пусто — у подарков, активированных до перехода на сетевую схему.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_gifts_activated_here', to='branch.branch', verbose_name='Точка активации (сетевой подарок)'),
        ),
    ]
