# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotype_image', models.ImageField(blank=True, help_text='Опционально — активируется при подключении платного брендинга', null=True, upload_to='config/logos/', verbose_name='Логотип')),
                ('coin_image', models.ImageField(blank=True, help_text='Опционально — активируется при подключении платного брендинга', null=True, upload_to='config/coins/', verbose_name='Иконка монеты')),
                ('vk_group_id', models.PositiveIntegerField(help_text='Числовой ID группы ВКонтакте. Отображается на фронте для подписки.', verbose_name='VK Group ID')),
                ('vk_group_name', models.CharField(help_text='Отображается в приложении рядом с кнопкой «Подписаться»', max_length=255, verbose_name='Название группы VK')),
                ('pos_type', models.CharField(choices=[('none', 'Не подключено'), ('iiko', 'iiko'), ('dooglys', 'Dooglys')], default='none', help_text='Выберите систему, которую использует клиент. Поля ниже активируются автоматически.', max_length=10, verbose_name='Кассовая система')),
                ('iiko_api_url', models.URLField(blank=True, help_text='Пример: https://iiko.biz/api/1/', verbose_name='IIKO API URL')),
                ('iiko_login', models.CharField(blank=True, help_text='Логин пользователя API из кабинета iiko.', max_length=255, verbose_name='IIKO Логин')),
                ('iiko_password', models.CharField(blank=True, help_text='Пароль пользователя API из кабинета iiko.', max_length=255, verbose_name='IIKO Пароль')),
                ('dooglys_api_url', models.URLField(blank=True, help_text='Пример: https://api.dooglys.com/v1/', verbose_name='Dooglys API URL')),
                ('dooglys_api_token', models.CharField(blank=True, help_text='API-ключ из личного кабинета Dooglys.', max_length=512, verbose_name='Dooglys API Token')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='clients.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройки клиента',
                'verbose_name_plural': 'Настройки клиентов',
            },
        ),
    ]
