# Generated by Django 6.0.3 on 2026-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_clientconfig_brand_color_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfig',
            name='story_activation_minutes',
            field=models.PositiveIntegerField(default=40, help_text='Сколько минут действует подарок после активации в кафе. По умолчанию 40.', verbose_name='Время действия подарка из сториз после активации, мин'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_activation_text',
            field=models.TextField(blank=True, default='', help_text='Что видит пользователь при попытке активировать подарок до визита в кафе. Поддерживаются переменные: [адрес кафе], [сумма], [время], [название кафе], [название подарка]. Пусто — стандартный текст по умолчанию.', verbose_name='Текст инструкции перед активацией (сториз)'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_cafe_address',
            field=models.CharField(blank=True, default='', help_text='Куда направляем пользователя за подарком. Пусто — берётся адрес точки.', max_length=255, verbose_name='Адрес кафе для подарка из сториз'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_campaign_end',
            field=models.DateField(blank=True, help_text='Опционально. После этой даты игра через сториз недоступна. Пусто — без ограничения.', null=True, verbose_name='Дата окончания кампании сториз'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_campaign_start',
            field=models.DateField(blank=True, help_text='Опционально. До этой даты игра через сториз недоступна. Пусто — без ограничения.', null=True, verbose_name='Дата начала кампании сториз'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_game_enabled',
            field=models.BooleanField(default=False, help_text='Разрешить внешним пользователям, пришедшим по сториз, играть и получать подарок. По умолчанию выключено.', verbose_name='Игра через сториз включена'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_min_order_amount',
            field=models.PositiveIntegerField(default=600, help_text='Минимальная сумма заказа для активации подарка из сториз. Подставляется в текст условий. 0 — без ограничения.', verbose_name='Мин. сумма заказа для подарка из сториз, ₽'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_require_cafe_visit',
            field=models.BooleanField(default=True, help_text='По умолчанию включено. Подарок из сториз активируется ТОЛЬКО после ввода кода дня в кафе — домашняя активация показывает инструкцию и не запускает таймер. Выключать не рекомендуется.', verbose_name='Требовать визит в кафе (код дня) перед активацией'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_saved_text',
            field=models.TextField(blank=True, default='', help_text='Сообщение «подарок сохранён в Мои подарки». Пусто — стандартный текст по умолчанию.', verbose_name='Текст уведомления после выбора подарка (сториз)'),
        ),
    ]
