# Generated by Django 6.0.3 on 2026-07-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_clientconfig_vk_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfig',
            name='story_gift_lifetime_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Сколько дней у гостя есть, чтобы активировать подарок в кафе. Отсчёт — от момента сохранения подарка в «Мои подарки». По истечении подарок сгорает. 0 — бессрочно.', verbose_name='Срок жизни подарка из сториз/сайта, дней'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='story_gift_reminder_days',
            field=models.PositiveSmallIntegerField(default=10, help_text='Через сколько дней после получения отправить VK-напоминание, если подарок так и не активирован. Текст — в «Шаблоны авторассылок» → «Подарок не забран». Должно быть меньше срока жизни. 0 — не напоминать.', verbose_name='Напомнить о неактивированном подарке через, дней'),
        ),
    ]
