# Generated by Django 6.0.3 on 2026-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_clientconfig_story_gift_lifetime_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfig',
            name='auto_broadcast_weekly_cap',
            field=models.PositiveSmallIntegerField(default=0, help_text='Максимум автоматических сообщений одному гостю за 7 дней. Защита от того, чтобы несколько правил не завалили человека. 0 — без ограничения (по умолчанию).', verbose_name='Лимит авторассылок на гостя в неделю'),
        ),
    ]
