# Generated by Django 6.0.3 on 2026-10-04 21:02

import apps.shared.secret_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_clientconfig_guest_phone_reward_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconfig',
            name='dooglys_api_token',
            field=apps.shared.secret_fields.EncryptedSecretField(blank=True, help_text='API-ключ из личного кабинета Dooglys.', max_length=512, verbose_name='Dooglys API Token'),
        ),
        migrations.AlterField(
            model_name='clientconfig',
            name='iiko_password',
            field=apps.shared.secret_fields.EncryptedSecretField(blank=True, help_text='Пароль пользователя API из кабинета iiko.', max_length=255, verbose_name='IIKO Пароль'),
        ),
    ]
