# Generated by Django 6.0.3 on 2026-10-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_alter_clientconfig_dooglys_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfig',
            name='rf_daily_contact_limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 — без ограничения. Максимум RF-сообщений в день по сети.', verbose_name='Лимит RF-сообщений в день'),
        ),
        migrations.AddField(
            model_name='clientconfig',
            name='rf_reward_max_cost_rub',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 — без ограничения. Максимальная себестоимость RF-подарка.', max_digits=10, verbose_name='Предел себестоимости RF-подарка, ₽'),
        ),
    ]
