# Generated by Django 6.0.3 on 2026-03-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('vk_id', models.PositiveIntegerField(help_text='Уникальный числовой ID пользователя ВКонтакте', unique=True, verbose_name='VK ID')),
                ('first_name', models.CharField(blank=True, help_text='Берётся из VK API.', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Берётся из VK API.', max_length=255, verbose_name='Фамилия')),
                ('photo_url', models.URLField(blank=True, help_text='Ссылка на аватар из VK.', verbose_name='Фото')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], default='', help_text='Берётся из VK API при регистрации (1 = женский, 2 = мужской).', max_length=1, null=True, verbose_name='Пол')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите флаг, чтобы заблокировать гостя на всей платформе', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'ordering': ['-created_at'],
            },
        ),
    ]
