# Generated by Django 6.0.3 on 2026-03-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Ссылка на аватар из VK.', max_length=500, verbose_name='Фото'),
        ),
    ]
