# Generated by Django 6.0.3 on 2026-04-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_photo_url_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], default=None, help_text='Берётся из VK API при регистрации (1 = женский, 2 = мужской).', max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
