# Generated by Django 6.0.3 on 2026-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vk_id',
            field=models.PositiveBigIntegerField(help_text='Уникальный числовой ID пользователя ВКонтакте', unique=True, verbose_name='VK ID'),
        ),
    ]
