# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attempts', to='branch.clientbranch', verbose_name='Гость')),
                ('served_by', models.ForeignKey(blank=True, help_text='Сотрудник (is_employee=True), которого гость выбрал после игры.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_game_attempts', to='branch.clientbranch', verbose_name='Официант')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='game_client_time_idx'), models.Index(fields=['served_by'], name='game_served_by_idx')],
            },
        ),
    ]
