# Generated by Django 6.0.3 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('reward', models.PositiveIntegerField(help_text='Сколько баллов начисляется за выполнение.', verbose_name='Награда (баллы)')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивный квест не виден гостям.', verbose_name='Активен')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, help_text='Меньшее значение отображается выше в списке гостей.', verbose_name='Порядок')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='branch.branch', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('activated_at', models.DateTimeField(help_text='Момент активации квеста гостем. Отсчёт таймера.', verbose_name='Активирован')),
                ('duration', models.PositiveIntegerField(default=40, help_text='Минут на выполнение после активации.', verbose_name='Длительность (мин)')),
                ('expires_at', models.DateTimeField(help_text='Устанавливается автоматически: activated_at + duration.', verbose_name='Истекает')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_submits', to='branch.clientbranch', verbose_name='Гость')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='quest.quest', verbose_name='Квест')),
                ('served_by', models.ForeignKey(blank=True, help_text='Сотрудник (is_employee=True), подтвердивший выполнение.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_quest_submits', to='branch.clientbranch', verbose_name='Официант')),
            ],
            options={
                'verbose_name': 'Выполнение квеста',
                'verbose_name_plural': 'Выполнения квестов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['branch', 'is_active'], name='quest_branch_active_idx'),
        ),
        migrations.AddIndex(
            model_name='questsubmit',
            index=models.Index(fields=['quest', 'completed_at'], name='qs_quest_complete_idx'),
        ),
        migrations.AddIndex(
            model_name='questsubmit',
            index=models.Index(fields=['client', 'completed_at'], name='qs_client_complete_idx'),
        ),
        migrations.AddIndex(
            model_name='questsubmit',
            index=models.Index(fields=['served_by'], name='qs_served_by_idx'),
        ),
        migrations.AddIndex(
            model_name='questsubmit',
            index=models.Index(fields=['expires_at'], name='qs_expires_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questsubmit',
            unique_together={('client', 'quest')},
        ),
    ]
